/*
 * Copyright (c) 2011 Sgine
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *  Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the distribution.
 *
 *  Neither the name of 'Sgine' nor the names of its contributors
 *   may be used to endorse or promote products derived from this software
 *   without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.sgine.opengl.lwjgl

import sys.error

/**
 * Generated by org.sgine.opengl.generator.OpenGLGenerator
 *
 * Documentation information pulled from <a href="http://www.opengl.org/sdk/docs/man/">http://www.opengl.org/sdk/docs/man/</a>.
 *
 * @see org.sgine.opengl.generator.OpenGLGenerator
 */
object GL extends org.sgine.opengl.GL {
	def glViewport(x: Int, y: Int, width: Int, height: Int): Unit = {
		org.lwjgl.opengl.GL11.glViewport(x, y, width, height)
	}

	def glVertexPointer(size: Int, `type`: Int, stride: Int, pointer: java.nio.Buffer): Unit = {
		pointer match {
			case conversion: java.nio.DoubleBuffer => org.lwjgl.opengl.GL11.glVertexPointer(size, stride, conversion)
			case conversion: java.nio.FloatBuffer => org.lwjgl.opengl.GL11.glVertexPointer(size, stride, conversion)
			case conversion: java.nio.IntBuffer => org.lwjgl.opengl.GL11.glVertexPointer(size, stride, conversion)
			case conversion: java.nio.ShortBuffer => org.lwjgl.opengl.GL11.glVertexPointer(size, stride, conversion)
			case _ => error("Failed conversion!")
		}
	}

	def glVertexPointer(size: Int, `type`: Int, stride: Int, offset: Int): Unit = {
		org.lwjgl.opengl.GL11.glVertexPointer(size, `type`, stride, offset)
	}

	def glTranslatef(x: Float, y: Float, z: Float): Unit = {
		org.lwjgl.opengl.GL11.glTranslatef(x, y, z)
	}

	def glTexSubImage2D(target: Int, level: Int, xoffset: Int, yoffset: Int, width: Int, height: Int, format: Int, `type`: Int, pixels: java.nio.Buffer): Unit = {
		pixels match {
			case conversion: java.nio.ByteBuffer => org.lwjgl.opengl.GL11.glTexSubImage2D(target, level, xoffset, yoffset, width, height, format, `type`, conversion)
			case conversion: java.nio.DoubleBuffer => org.lwjgl.opengl.GL11.glTexSubImage2D(target, level, xoffset, yoffset, width, height, format, `type`, conversion)
			case conversion: java.nio.FloatBuffer => org.lwjgl.opengl.GL11.glTexSubImage2D(target, level, xoffset, yoffset, width, height, format, `type`, conversion)
			case conversion: java.nio.IntBuffer => org.lwjgl.opengl.GL11.glTexSubImage2D(target, level, xoffset, yoffset, width, height, format, `type`, conversion)
			case conversion: java.nio.ShortBuffer => org.lwjgl.opengl.GL11.glTexSubImage2D(target, level, xoffset, yoffset, width, height, format, `type`, conversion)
			case _ => error("Failed conversion!")
		}
	}

	def glTexParameter(target: Int, pname: Int, params: java.nio.FloatBuffer): Unit = {
		org.lwjgl.opengl.GL11.glTexParameter(target, pname, params)
	}

	def glTexParameter(target: Int, pname: Int, params: java.nio.IntBuffer): Unit = {
		org.lwjgl.opengl.GL30.glTexParameterIu(target, pname, params)
	}

	def glTexParameter(target: Int, pname: Int, param: Int): Unit = {
		org.lwjgl.opengl.GL30.glTexParameterIi(target, pname, param)
	}

	def glTexParameterf(target: Int, pname: Int, param: Float): Unit = {
		org.lwjgl.opengl.GL11.glTexParameterf(target, pname, param)
	}

	def glTexParameteri(target: Int, pname: Int, param: Int): Unit = {
		org.lwjgl.opengl.GL11.glTexParameteri(target, pname, param)
	}

	def glTexImage2D(target: Int, level: Int, internalformat: Int, width: Int, height: Int, border: Int, format: Int, `type`: Int, pixels: java.nio.Buffer): Unit = {
		pixels match {
			case conversion: java.nio.ByteBuffer => org.lwjgl.opengl.GL11.glTexImage2D(target, level, internalformat, width, height, border, format, `type`, conversion)
			case conversion: java.nio.DoubleBuffer => org.lwjgl.opengl.GL11.glTexImage2D(target, level, internalformat, width, height, border, format, `type`, conversion)
			case conversion: java.nio.FloatBuffer => org.lwjgl.opengl.GL11.glTexImage2D(target, level, internalformat, width, height, border, format, `type`, conversion)
			case conversion: java.nio.IntBuffer => org.lwjgl.opengl.GL11.glTexImage2D(target, level, internalformat, width, height, border, format, `type`, conversion)
			case conversion: java.nio.ShortBuffer => org.lwjgl.opengl.GL11.glTexImage2D(target, level, internalformat, width, height, border, format, `type`, conversion)
			case _ => error("Failed conversion!")
		}
	}

	def glTexEnv(target: Int, pname: Int, params: java.nio.FloatBuffer): Unit = {
		org.lwjgl.opengl.GL11.glTexEnv(target, pname, params)
	}

	def glTexEnv(target: Int, pname: Int, params: java.nio.IntBuffer): Unit = {
		org.lwjgl.opengl.GL11.glTexEnv(target, pname, params)
	}

	def glTexEnvf(target: Int, pname: Int, param: Float): Unit = {
		org.lwjgl.opengl.GL11.glTexEnvf(target, pname, param)
	}

	def glTexEnvi(target: Int, pname: Int, param: Int): Unit = {
		org.lwjgl.opengl.GL11.glTexEnvi(target, pname, param)
	}

	def glTexCoordPointer(size: Int, `type`: Int, stride: Int, pointer: java.nio.Buffer): Unit = {
		pointer match {
			case conversion: java.nio.DoubleBuffer => org.lwjgl.opengl.GL11.glTexCoordPointer(size, stride, conversion)
			case conversion: java.nio.FloatBuffer => org.lwjgl.opengl.GL11.glTexCoordPointer(size, stride, conversion)
			case conversion: java.nio.IntBuffer => org.lwjgl.opengl.GL11.glTexCoordPointer(size, stride, conversion)
			case conversion: java.nio.ShortBuffer => org.lwjgl.opengl.GL11.glTexCoordPointer(size, stride, conversion)
			case _ => error("Failed conversion!")
		}
	}

	def glTexCoordPointer(size: Int, `type`: Int, stride: Int, offset: Int): Unit = {
		org.lwjgl.opengl.GL11.glTexCoordPointer(size, `type`, stride, offset)
	}

	def glStencilOp(fail: Int, zfail: Int, zpass: Int): Unit = {
		org.lwjgl.opengl.GL11.glStencilOp(fail, zfail, zpass)
	}

	def glStencilMask(mask: Int): Unit = {
		org.lwjgl.opengl.GL11.glStencilMask(mask)
	}

	def glStencilFunc(func: Int, ref: Int, mask: Int): Unit = {
		org.lwjgl.opengl.GL11.glStencilFunc(func, ref, mask)
	}

	def glShadeModel(mode: Int): Unit = {
		org.lwjgl.opengl.GL11.glShadeModel(mode)
	}

	def glScissor(x: Int, y: Int, width: Int, height: Int): Unit = {
		org.lwjgl.opengl.GL11.glScissor(x, y, width, height)
	}

	def glScalef(x: Float, y: Float, z: Float): Unit = {
		org.lwjgl.opengl.GL11.glScalef(x, y, z)
	}

	def glSampleCoverage(value: Float, invert: Boolean): Unit = {
		org.lwjgl.opengl.GL13.glSampleCoverage(value, invert)
	}

	def glRotatef(angle: Float, x: Float, y: Float, z: Float): Unit = {
		org.lwjgl.opengl.GL11.glRotatef(angle, x, y, z)
	}

	def glReadPixels(x: Int, y: Int, width: Int, height: Int, format: Int, `type`: Int, pixels: java.nio.Buffer): Unit = {
		pixels match {
			case conversion: java.nio.ByteBuffer => org.lwjgl.opengl.GL11.glReadPixels(x, y, width, height, format, `type`, conversion)
			case conversion: java.nio.DoubleBuffer => org.lwjgl.opengl.GL11.glReadPixels(x, y, width, height, format, `type`, conversion)
			case conversion: java.nio.FloatBuffer => org.lwjgl.opengl.GL11.glReadPixels(x, y, width, height, format, `type`, conversion)
			case conversion: java.nio.IntBuffer => org.lwjgl.opengl.GL11.glReadPixels(x, y, width, height, format, `type`, conversion)
			case conversion: java.nio.ShortBuffer => org.lwjgl.opengl.GL11.glReadPixels(x, y, width, height, format, `type`, conversion)
			case _ => error("Failed conversion!")
		}
	}

	def glPushMatrix(): Unit = {
		org.lwjgl.opengl.GL11.glPushMatrix()
	}

	def glPopMatrix(): Unit = {
		org.lwjgl.opengl.GL11.glPopMatrix()
	}

	def glPolygonOffset(factor: Float, units: Float): Unit = {
		org.lwjgl.opengl.GL11.glPolygonOffset(factor, units)
	}

	def glPointSize(size: Float): Unit = {
		org.lwjgl.opengl.GL11.glPointSize(size)
	}

	def glPointParameter(pname: Int, params: java.nio.FloatBuffer): Unit = {
		org.lwjgl.opengl.GL14.glPointParameter(pname, params)
	}

	def glPointParameter(pname: Int, param: Int): Unit = {
		org.lwjgl.opengl.GL14.glPointParameteri(pname, param)
	}

	def glPointParameter(pname: Int, params: java.nio.IntBuffer): Unit = {
		org.lwjgl.opengl.GL14.glPointParameter(pname, params)
	}

	def glPointParameterf(pname: Int, param: Float): Unit = {
		org.lwjgl.opengl.GL14.glPointParameterf(pname, param)
	}

	def glPixelStorei(pname: Int, param: Int): Unit = {
		org.lwjgl.opengl.GL11.glPixelStorei(pname, param)
	}

	def glOrtho(left: Float, right: Float, bottom: Float, top: Float, zNear: Float, zFar: Float): Unit = {
		org.lwjgl.opengl.GL11.glOrtho(left, right, bottom, top, zNear, zFar)
	}

	def glNormalPointer(`type`: Int, stride: Int, pointer: java.nio.Buffer): Unit = {
		pointer match {
			case conversion: java.nio.ByteBuffer => org.lwjgl.opengl.GL11.glNormalPointer(stride, conversion)
			case conversion: java.nio.DoubleBuffer => org.lwjgl.opengl.GL11.glNormalPointer(stride, conversion)
			case conversion: java.nio.FloatBuffer => org.lwjgl.opengl.GL11.glNormalPointer(stride, conversion)
			case conversion: java.nio.IntBuffer => org.lwjgl.opengl.GL11.glNormalPointer(stride, conversion)
			case _ => error("Failed conversion!")
		}
	}

	def glNormalPointer(`type`: Int, stride: Int, offset: Int): Unit = {
		org.lwjgl.opengl.GL11.glNormalPointer(`type`, stride, offset)
	}

	def glNormal(nx: Int, ny: Int, nz: Int): Unit = {
		org.lwjgl.opengl.GL11.glNormal3i(nx, ny, nz)
	}

	def glNormal3f(nx: Float, ny: Float, nz: Float): Unit = {
		org.lwjgl.opengl.GL11.glNormal3f(nx, ny, nz)
	}

	def glMultiTexCoord4f(target: Int, s: Float, t: Float, r: Float, q: Float): Unit = {
		org.lwjgl.opengl.GL13.glMultiTexCoord4f(target, s, t, r, q)
	}

	def glMultMatrix(m: java.nio.FloatBuffer): Unit = {
		org.lwjgl.opengl.GL11.glMultMatrix(m)
	}

	def glMatrixMode(mode: Int): Unit = {
		org.lwjgl.opengl.GL11.glMatrixMode(mode)
	}

	def glMaterial(face: Int, pname: Int, params: java.nio.FloatBuffer): Unit = {
		org.lwjgl.opengl.GL11.glMaterial(face, pname, params)
	}

	def glMaterial(face: Int, pname: Int, param: Int): Unit = {
		org.lwjgl.opengl.GL11.glMateriali(face, pname, param)
	}

	def glMaterial(face: Int, pname: Int, params: java.nio.IntBuffer): Unit = {
		org.lwjgl.opengl.GL11.glMaterial(face, pname, params)
	}

	def glMaterialf(face: Int, pname: Int, param: Float): Unit = {
		org.lwjgl.opengl.GL11.glMaterialf(face, pname, param)
	}

	def glLogicOp(opcode: Int): Unit = {
		org.lwjgl.opengl.GL11.glLogicOp(opcode)
	}

	def glLoadMatrix(m: java.nio.FloatBuffer): Unit = {
		org.lwjgl.opengl.GL11.glLoadMatrix(m)
	}

	def glLoadIdentity(): Unit = {
		org.lwjgl.opengl.GL11.glLoadIdentity()
	}

	def glLineWidth(width: Float): Unit = {
		org.lwjgl.opengl.GL11.glLineWidth(width)
	}

	def glLightModel(pname: Int, params: java.nio.FloatBuffer): Unit = {
		org.lwjgl.opengl.GL11.glLightModel(pname, params)
	}

	def glLightModel(pname: Int, param: Int): Unit = {
		org.lwjgl.opengl.GL11.glLightModeli(pname, param)
	}

	def glLightModel(pname: Int, params: java.nio.IntBuffer): Unit = {
		org.lwjgl.opengl.GL11.glLightModel(pname, params)
	}

	def glLightModelf(pname: Int, param: Float): Unit = {
		org.lwjgl.opengl.GL11.glLightModelf(pname, param)
	}

	def glLight(light: Int, pname: Int, params: java.nio.FloatBuffer): Unit = {
		org.lwjgl.opengl.GL11.glLight(light, pname, params)
	}

	def glLight(light: Int, pname: Int, param: Int): Unit = {
		org.lwjgl.opengl.GL11.glLighti(light, pname, param)
	}

	def glLight(light: Int, pname: Int, params: java.nio.IntBuffer): Unit = {
		org.lwjgl.opengl.GL11.glLight(light, pname, params)
	}

	def glLightf(light: Int, pname: Int, param: Float): Unit = {
		org.lwjgl.opengl.GL11.glLightf(light, pname, param)
	}

	def glIsTexture(texture: Int): Boolean = {
		org.lwjgl.opengl.GL11.glIsTexture(texture)
	}

	def glIsEnabled(cap: Int): Boolean = {
		org.lwjgl.opengl.GL11.glIsEnabled(cap)
	}

	def glIsBuffer(buffer: Int): Boolean = {
		org.lwjgl.opengl.GL15.glIsBuffer(buffer)
	}

	def glHint(target: Int, mode: Int): Unit = {
		org.lwjgl.opengl.GL11.glHint(target, mode)
	}

	def glGetTexParameter(target: Int, pname: Int, params: java.nio.FloatBuffer): Unit = {
		org.lwjgl.opengl.GL11.glGetTexParameter(target, pname, params)
	}

	def glGetTexParameter(target: Int, pname: Int, params: java.nio.IntBuffer): Unit = {
		org.lwjgl.opengl.GL30.glGetTexParameterIu(target, pname, params)
	}

	def glGetTexEnv(env: Int, pname: Int, params: java.nio.IntBuffer): Unit = {
		org.lwjgl.opengl.GL11.glGetTexEnv(env, pname, params)
	}

	def glGetString(name: Int): String = {
		org.lwjgl.opengl.GL11.glGetString(name)
	}

	def glGetMaterial(face: Int, pname: Int, params: java.nio.FloatBuffer): Unit = {
		org.lwjgl.opengl.GL11.glGetMaterial(face, pname, params)
	}

	def glGetMaterial(face: Int, pname: Int, params: java.nio.IntBuffer): Unit = {
		org.lwjgl.opengl.GL11.glGetMaterial(face, pname, params)
	}

	def glGetLight(light: Int, pname: Int, params: java.nio.FloatBuffer): Unit = {
		org.lwjgl.opengl.GL11.glGetLight(light, pname, params)
	}

	def glGetLight(light: Int, pname: Int, params: java.nio.IntBuffer): Unit = {
		org.lwjgl.opengl.GL11.glGetLight(light, pname, params)
	}

	def glGetError(): Int = {
		org.lwjgl.opengl.GL11.glGetError()
	}

	def glFrustum(left: Float, right: Float, bottom: Float, top: Float, zNear: Float, zFar: Float): Unit = {
		org.lwjgl.opengl.GL11.glFrustum(left, right, bottom, top, zNear, zFar)
	}

	def glFrontFace(mode: Int): Unit = {
		org.lwjgl.opengl.GL11.glFrontFace(mode)
	}

	def glFog(pname: Int, params: java.nio.FloatBuffer): Unit = {
		org.lwjgl.opengl.GL11.glFog(pname, params)
	}

	def glFog(pname: Int, param: Int): Unit = {
		org.lwjgl.opengl.GL11.glFogi(pname, param)
	}

	def glFog(pname: Int, params: java.nio.IntBuffer): Unit = {
		org.lwjgl.opengl.GL11.glFog(pname, params)
	}

	def glFogf(pname: Int, param: Float): Unit = {
		org.lwjgl.opengl.GL11.glFogf(pname, param)
	}

	def glFlush(): Unit = {
		org.lwjgl.opengl.GL11.glFlush()
	}

	def glFinish(): Unit = {
		org.lwjgl.opengl.GL11.glFinish()
	}

	def glEnableClientState(array: Int): Unit = {
		org.lwjgl.opengl.GL11.glEnableClientState(array)
	}

	def glEnable(cap: Int): Unit = {
		org.lwjgl.opengl.GL11.glEnable(cap)
	}

	def glDrawElements(mode: Int, count: Int, `type`: Int, indices: java.nio.Buffer): Unit = {
		indices match {
			case conversion: java.nio.ByteBuffer => org.lwjgl.opengl.GL11.glDrawElements(mode, conversion)
			case conversion: java.nio.IntBuffer => org.lwjgl.opengl.GL11.glDrawElements(mode, conversion)
			case conversion: java.nio.ShortBuffer => org.lwjgl.opengl.GL11.glDrawElements(mode, conversion)
			case _ => error("Failed conversion!")
		}
	}

	def glDrawElements(mode: Int, count: Int, `type`: Int, offset: Int): Unit = {
		org.lwjgl.opengl.GL11.glDrawElements(mode, count, `type`, offset)
	}

	def glDrawArrays(mode: Int, first: Int, count: Int): Unit = {
		org.lwjgl.opengl.GL11.glDrawArrays(mode, first, count)
	}

	def glDisableClientState(array: Int): Unit = {
		org.lwjgl.opengl.GL11.glDisableClientState(array)
	}

	def glDisable(cap: Int): Unit = {
		org.lwjgl.opengl.GL11.glDisable(cap)
	}

	def glDepthRangef(zNear: Float, zFar: Float): Unit = {
		org.lwjgl.opengl.GL41.glDepthRangef(zNear, zFar)
	}

	def glDepthMask(flag: Boolean): Unit = {
		org.lwjgl.opengl.GL11.glDepthMask(flag)
	}

	def glDepthFunc(func: Int): Unit = {
		org.lwjgl.opengl.GL11.glDepthFunc(func)
	}

	def glCullFace(mode: Int): Unit = {
		org.lwjgl.opengl.GL11.glCullFace(mode)
	}

	def glCopyTexSubImage2D(target: Int, level: Int, xoffset: Int, yoffset: Int, x: Int, y: Int, width: Int, height: Int): Unit = {
		org.lwjgl.opengl.GL11.glCopyTexSubImage2D(target, level, xoffset, yoffset, x, y, width, height)
	}

	def glCopyTexImage2D(target: Int, level: Int, internalformat: Int, x: Int, y: Int, width: Int, height: Int, border: Int): Unit = {
		org.lwjgl.opengl.GL11.glCopyTexImage2D(target, level, internalformat, x, y, width, height, border)
	}

	def glColorPointer(size: Int, `type`: Int, stride: Int, pointer: java.nio.Buffer): Unit = {
		pointer match {
			case conversion: java.nio.DoubleBuffer => org.lwjgl.opengl.GL11.glColorPointer(size, stride, conversion)
			case conversion: java.nio.FloatBuffer => org.lwjgl.opengl.GL11.glColorPointer(size, stride, conversion)
			case _ => error("Failed conversion!")
		}
	}

	def glColorPointer(size: Int, `type`: Int, stride: Int, offset: Int): Unit = {
		org.lwjgl.opengl.GL11.glColorPointer(size, `type`, stride, offset)
	}

	def glColorMask(red: Boolean, green: Boolean, blue: Boolean, alpha: Boolean): Unit = {
		org.lwjgl.opengl.GL11.glColorMask(red, green, blue, alpha)
	}

	def glColor4f(red: Float, green: Float, blue: Float, alpha: Float): Unit = {
		org.lwjgl.opengl.GL11.glColor4f(red, green, blue, alpha)
	}

	def glClientActiveTexture(texture: Int): Unit = {
		org.lwjgl.opengl.GL13.glClientActiveTexture(texture)
	}

	def glClearStencil(s: Int): Unit = {
		org.lwjgl.opengl.GL11.glClearStencil(s)
	}

	def glClearDepthf(depth: Float): Unit = {
		org.lwjgl.opengl.GL41.glClearDepthf(depth)
	}

	def glClearColor(red: Float, green: Float, blue: Float, alpha: Float): Unit = {
		org.lwjgl.opengl.GL11.glClearColor(red, green, blue, alpha)
	}

	def glClear(mask: Int): Unit = {
		org.lwjgl.opengl.GL11.glClear(mask)
	}

	def glBufferSubData(target: Int, offset: Int, size: Int, data: java.nio.Buffer): Unit = {
		data match {
			case conversion: java.nio.ByteBuffer => org.lwjgl.opengl.GL15.glBufferSubData(target, offset, conversion)
			case conversion: java.nio.DoubleBuffer => org.lwjgl.opengl.GL15.glBufferSubData(target, offset, conversion)
			case conversion: java.nio.FloatBuffer => org.lwjgl.opengl.GL15.glBufferSubData(target, offset, conversion)
			case conversion: java.nio.IntBuffer => org.lwjgl.opengl.GL15.glBufferSubData(target, offset, conversion)
			case conversion: java.nio.ShortBuffer => org.lwjgl.opengl.GL15.glBufferSubData(target, offset, conversion)
			case _ => error("Failed conversion!")
		}
	}

	def glBufferData(target: Int, size: Int, data: java.nio.Buffer, usage: Int): Unit = {
		data match {
			case conversion: java.nio.ByteBuffer => org.lwjgl.opengl.GL15.glBufferData(target, conversion, usage)
			case conversion: java.nio.DoubleBuffer => org.lwjgl.opengl.GL15.glBufferData(target, conversion, usage)
			case conversion: java.nio.FloatBuffer => org.lwjgl.opengl.GL15.glBufferData(target, conversion, usage)
			case conversion: java.nio.IntBuffer => org.lwjgl.opengl.GL15.glBufferData(target, conversion, usage)
			case conversion: java.nio.ShortBuffer => org.lwjgl.opengl.GL15.glBufferData(target, conversion, usage)
			case _ => error("Failed conversion!")
		}
	}

	def glBlendFunc(sfactor: Int, dfactor: Int): Unit = {
		org.lwjgl.opengl.GL11.glBlendFunc(sfactor, dfactor)
	}

	def glBindTexture(target: Int, texture: Int): Unit = {
		org.lwjgl.opengl.GL11.glBindTexture(target, texture)
	}

	def glBindBuffer(target: Int, buffer: Int): Unit = {
		org.lwjgl.opengl.GL15.glBindBuffer(target, buffer)
	}

	def glAlphaFunc(func: Int, ref: Float): Unit = {
		org.lwjgl.opengl.GL11.glAlphaFunc(func, ref)
	}

	def glActiveTexture(texture: Int): Unit = {
		org.lwjgl.opengl.GL13.glActiveTexture(texture)
	}
}