package org.sgine.opengl

/**
 * Generated by org.sgine.opengl.generator.Generator
 * 
 * Documentation information pulled from <a href="http://www.opengl.org/sdk/docs/man/">http://www.opengl.org/sdk/docs/man/</a>.
 * 
 * @see org.sgine.opengl.generator.Generator
 */
trait GL {
	/**
	 */
	def glActiveTexture(): Unit

	/**
	 */
	def glAlphaFunc(): Unit

	/**
	 */
	def glBindBuffer(): Unit

	/**
	 */
	def glBindTexture(): Unit

	/**
	 */
	def glBlendFunc(): Unit

	/**
	 */
	def glBufferData(): Unit

	/**
	 */
	def glBufferSubData(): Unit

	/**
	 */
	def glClear(): Unit

	/**
	 */
	def glClearColor(): Unit

	/**
	 */
	def glClearDepth(): Unit

	/**
	 */
	def glClearStencil(): Unit

	/**
	 */
	def glClientActiveTexture(): Unit

	/**
	 */
	def glClipPlane(): Unit

	/**
	 */
	def glColor(): Unit

	/**
	 */
	def glColorMask(): Unit

	/**
	 */
	def glColorPointer(): Unit

	/**
	 */
	def glCompressedTexImage2D(): Unit

	/**
	 */
	def glCompressedTexSubImage2D(): Unit

	/**
	 */
	def glCopyTexImage2D(): Unit

	/**
	 */
	def glCopyTexSubImage2D(): Unit

	/**
	 */
	def glCullFace(): Unit

	/**
	 */
	def glDeleteBuffers(): Unit

	/**
	 */
	def glDeleteTextures(): Unit

	/**
	 */
	def glDepthFunc(): Unit

	/**
	 */
	def glDepthMask(): Unit

	/**
	 */
	def glDepthRange(): Unit

	/**
	 */
	def glDisable(): Unit

	/**
	 */
	def glDisableClientState(): Unit

	/**
	 */
	def glDrawArrays(): Unit

	/**
	 */
	def glDrawElements(): Unit

	/**
	 */
	def glEnable(): Unit

	/**
	 */
	def glEnableClientState(): Unit

	/**
	 */
	def glFinish(): Unit

	/**
	 */
	def glFlush(): Unit

	/**
	 */
	def glFog(): Unit

	/**
	 */
	def glFrontFace(): Unit

	/**
	 */
	def glFrustum(): Unit

	/**
	 */
	def glGenBuffers(): Unit

	/**
	 */
	def glGenTextures(): Unit

	/**
	 */
	def glGetClipPlane(): Unit

	/**
	 */
	def glGetError(): Unit

	/**
	 */
	def glGetLight(): Unit

	/**
	 */
	def glGetMaterial(): Unit

	/**
	 */
	def glGetString(): Unit

	/**
	 */
	def glGetTexEnv(): Unit

	/**
	 */
	def glGetTexParameter(): Unit

	/**
	 */
	def glHint(): Unit

	/**
	 */
	def glIsBuffer(): Unit

	/**
	 */
	def glIsEnabled(): Unit

	/**
	 */
	def glIsTexture(): Unit

	/**
	 */
	def glLight(): Unit

	/**
	 */
	def glLightModel(): Unit

	/**
	 */
	def glLineWidth(): Unit

	/**
	 */
	def glLoadIdentity(): Unit

	/**
	 */
	def glLoadMatrix(): Unit

	/**
	 */
	def glLogicOp(): Unit

	/**
	 */
	def glMaterial(): Unit

	/**
	 */
	def glMatrixMode(): Unit

	/**
	 */
	def glMultMatrix(): Unit

	/**
	 */
	def glMultiTexCoord(): Unit

	/**
	 */
	def glNormal(): Unit

	/**
	 */
	def glNormalPointer(): Unit

	/**
	 */
	def glOrtho(): Unit

	/**
	 */
	def glPixelStore(): Unit

	/**
	 */
	def glPointParameter(): Unit

	/**
	 */
	def glPointSize(): Unit

	/**
	 */
	def glPolygonOffset(): Unit

	/**
	 */
	def glPopMatrix(): Unit

	/**
	 */
	def glPushMatrix(): Unit

	/**
	 */
	def glReadPixels(): Unit

	/**
	 */
	def glRotate(): Unit

	/**
	 */
	def glSampleCoverage(): Unit

	/**
	 */
	def glScale(): Unit

	/**
	 */
	def glScissor(): Unit

	/**
	 */
	def glShadeModel(): Unit

	/**
	 */
	def glStencilFunc(): Unit

	/**
	 */
	def glStencilMask(): Unit

	/**
	 */
	def glStencilOp(): Unit

	/**
	 */
	def glTexCoordPointer(): Unit

	/**
	 */
	def glTexEnv(): Unit

	/**
	 */
	def glTexImage2D(): Unit

	/**
	 */
	def glTexParameter(): Unit

	/**
	 */
	def glTexSubImage2D(): Unit

	/**
	 */
	def glTranslate(): Unit

	/**
	 */
	def glVertexPointer(): Unit

	/**
	 */
	def glViewport(): Unit
}

object GL extends GL {
	/**
	 * Constant Value: 34016
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_ACTIVE_TEXTURE
	 * @see org.lwjgl.opengl.GL13#GL_ACTIVE_TEXTURE
	 */
	val GL_ACTIVE_TEXTURE: Int = 34016

	/**
	 * Constant Value: 260
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_ADD
	 * @see org.lwjgl.opengl.GL11#GL_ADD
	 */
	val GL_ADD: Int = 260

	/**
	 * Constant Value: 34164
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_ADD_SIGNED
	 * @see org.lwjgl.opengl.GL13#GL_ADD_SIGNED
	 */
	val GL_ADD_SIGNED: Int = 34164

	/**
	 * Constant Value: 33902
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_ALIASED_LINE_WIDTH_RANGE
	 * @see org.lwjgl.opengl.GL12#GL_ALIASED_LINE_WIDTH_RANGE
	 */
	val GL_ALIASED_LINE_WIDTH_RANGE: Int = 33902

	/**
	 * Constant Value: 33901
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_ALIASED_POINT_SIZE_RANGE
	 * @see org.lwjgl.opengl.GL12#GL_ALIASED_POINT_SIZE_RANGE
	 */
	val GL_ALIASED_POINT_SIZE_RANGE: Int = 33901

	/**
	 * Constant Value: 6406
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_ALPHA
	 * @see org.lwjgl.opengl.GL11#GL_ALPHA
	 */
	val GL_ALPHA: Int = 6406

	/**
	 * Constant Value: 3413
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_ALPHA_BITS
	 * @see org.lwjgl.opengl.GL11#GL_ALPHA_BITS
	 */
	val GL_ALPHA_BITS: Int = 3413

	/**
	 * Constant Value: 3356
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_ALPHA_SCALE
	 * @see org.lwjgl.opengl.GL11#GL_ALPHA_SCALE
	 */
	val GL_ALPHA_SCALE: Int = 3356

	/**
	 * Constant Value: 3008
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_ALPHA_TEST
	 * @see org.lwjgl.opengl.GL11#GL_ALPHA_TEST
	 */
	val GL_ALPHA_TEST: Int = 3008

	/**
	 * Constant Value: 3009
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_ALPHA_TEST_FUNC
	 * @see org.lwjgl.opengl.GL11#GL_ALPHA_TEST_FUNC
	 */
	val GL_ALPHA_TEST_FUNC: Int = 3009

	/**
	 * Constant Value: 3010
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_ALPHA_TEST_REF
	 * @see org.lwjgl.opengl.GL11#GL_ALPHA_TEST_REF
	 */
	val GL_ALPHA_TEST_REF: Int = 3010

	/**
	 * Constant Value: 519
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_ALWAYS
	 * @see org.lwjgl.opengl.GL11#GL_ALWAYS
	 */
	val GL_ALWAYS: Int = 519

	/**
	 * Constant Value: 4608
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_AMBIENT
	 * @see org.lwjgl.opengl.GL11#GL_AMBIENT
	 */
	val GL_AMBIENT: Int = 4608

	/**
	 * Constant Value: 5634
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_AMBIENT_AND_DIFFUSE
	 * @see org.lwjgl.opengl.GL11#GL_AMBIENT_AND_DIFFUSE
	 */
	val GL_AMBIENT_AND_DIFFUSE: Int = 5634

	/**
	 * Constant Value: 5377
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_AND
	 * @see org.lwjgl.opengl.GL11#GL_AND
	 */
	val GL_AND: Int = 5377

	/**
	 * Constant Value: 5380
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_AND_INVERTED
	 * @see org.lwjgl.opengl.GL11#GL_AND_INVERTED
	 */
	val GL_AND_INVERTED: Int = 5380

	/**
	 * Constant Value: 5378
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_AND_REVERSE
	 * @see org.lwjgl.opengl.GL11#GL_AND_REVERSE
	 */
	val GL_AND_REVERSE: Int = 5378

	/**
	 * Constant Value: 34962
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_ARRAY_BUFFER
	 * @see org.lwjgl.opengl.GL15#GL_ARRAY_BUFFER
	 */
	val GL_ARRAY_BUFFER: Int = 34962

	/**
	 * Constant Value: 34964
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_ARRAY_BUFFER_BINDING
	 * @see org.lwjgl.opengl.GL15#GL_ARRAY_BUFFER_BINDING
	 */
	val GL_ARRAY_BUFFER_BINDING: Int = 34964

	/**
	 * Constant Value: 1029
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_BACK
	 * @see org.lwjgl.opengl.GL11#GL_BACK
	 */
	val GL_BACK: Int = 1029

	/**
	 * Constant Value: 3042
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_BLEND
	 * @see org.lwjgl.opengl.GL11#GL_BLEND
	 */
	val GL_BLEND: Int = 3042

	/**
	 * Constant Value: 3040
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_BLEND_DST
	 * @see org.lwjgl.opengl.GL11#GL_BLEND_DST
	 */
	val GL_BLEND_DST: Int = 3040

	/**
	 * Constant Value: 3041
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_BLEND_SRC
	 * @see org.lwjgl.opengl.GL11#GL_BLEND_SRC
	 */
	val GL_BLEND_SRC: Int = 3041

	/**
	 * Constant Value: 3412
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_BLUE_BITS
	 * @see org.lwjgl.opengl.GL11#GL_BLUE_BITS
	 */
	val GL_BLUE_BITS: Int = 3412

	/**
	 * Constant Value: 35003
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_BUFFER_ACCESS
	 * @see org.lwjgl.opengl.GL15#GL_BUFFER_ACCESS
	 */
	val GL_BUFFER_ACCESS: Int = 35003

	/**
	 * Constant Value: 34660
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_BUFFER_SIZE
	 * @see org.lwjgl.opengl.GL15#GL_BUFFER_SIZE
	 */
	val GL_BUFFER_SIZE: Int = 34660

	/**
	 * Constant Value: 34661
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_BUFFER_USAGE
	 * @see org.lwjgl.opengl.GL15#GL_BUFFER_USAGE
	 */
	val GL_BUFFER_USAGE: Int = 34661

	/**
	 * Constant Value: 5120
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_BYTE
	 * @see org.lwjgl.opengl.GL11#GL_BYTE
	 */
	val GL_BYTE: Int = 5120

	/**
	 * Constant Value: 2305
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_CCW
	 * @see org.lwjgl.opengl.GL11#GL_CCW
	 */
	val GL_CCW: Int = 2305

	/**
	 * Constant Value: 33071
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_CLAMP_TO_EDGE
	 * @see org.lwjgl.opengl.GL12#GL_CLAMP_TO_EDGE
	 */
	val GL_CLAMP_TO_EDGE: Int = 33071

	/**
	 * Constant Value: 5376
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_CLEAR
	 * @see org.lwjgl.opengl.GL11#GL_CLEAR
	 */
	val GL_CLEAR: Int = 5376

	/**
	 * Constant Value: 34017
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_CLIENT_ACTIVE_TEXTURE
	 * @see org.lwjgl.opengl.GL13#GL_CLIENT_ACTIVE_TEXTURE
	 */
	val GL_CLIENT_ACTIVE_TEXTURE: Int = 34017

	/**
	 * Constant Value: 12288
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_CLIP_PLANE0
	 * @see org.lwjgl.opengl.GL11#GL_CLIP_PLANE0
	 */
	val GL_CLIP_PLANE0: Int = 12288

	/**
	 * Constant Value: 12289
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_CLIP_PLANE1
	 * @see org.lwjgl.opengl.GL11#GL_CLIP_PLANE1
	 */
	val GL_CLIP_PLANE1: Int = 12289

	/**
	 * Constant Value: 12290
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_CLIP_PLANE2
	 * @see org.lwjgl.opengl.GL11#GL_CLIP_PLANE2
	 */
	val GL_CLIP_PLANE2: Int = 12290

	/**
	 * Constant Value: 12291
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_CLIP_PLANE3
	 * @see org.lwjgl.opengl.GL11#GL_CLIP_PLANE3
	 */
	val GL_CLIP_PLANE3: Int = 12291

	/**
	 * Constant Value: 12292
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_CLIP_PLANE4
	 * @see org.lwjgl.opengl.GL11#GL_CLIP_PLANE4
	 */
	val GL_CLIP_PLANE4: Int = 12292

	/**
	 * Constant Value: 12293
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_CLIP_PLANE5
	 * @see org.lwjgl.opengl.GL11#GL_CLIP_PLANE5
	 */
	val GL_CLIP_PLANE5: Int = 12293

	/**
	 * Constant Value: 32886
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_COLOR_ARRAY
	 * @see org.lwjgl.opengl.GL11#GL_COLOR_ARRAY
	 */
	val GL_COLOR_ARRAY: Int = 32886

	/**
	 * Constant Value: 34968
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_COLOR_ARRAY_BUFFER_BINDING
	 * @see org.lwjgl.opengl.GL15#GL_COLOR_ARRAY_BUFFER_BINDING
	 */
	val GL_COLOR_ARRAY_BUFFER_BINDING: Int = 34968

	/**
	 * Constant Value: 32912
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_COLOR_ARRAY_POINTER
	 * @see org.lwjgl.opengl.GL11#GL_COLOR_ARRAY_POINTER
	 */
	val GL_COLOR_ARRAY_POINTER: Int = 32912

	/**
	 * Constant Value: 32897
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_COLOR_ARRAY_SIZE
	 * @see org.lwjgl.opengl.GL11#GL_COLOR_ARRAY_SIZE
	 */
	val GL_COLOR_ARRAY_SIZE: Int = 32897

	/**
	 * Constant Value: 32899
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_COLOR_ARRAY_STRIDE
	 * @see org.lwjgl.opengl.GL11#GL_COLOR_ARRAY_STRIDE
	 */
	val GL_COLOR_ARRAY_STRIDE: Int = 32899

	/**
	 * Constant Value: 32898
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_COLOR_ARRAY_TYPE
	 * @see org.lwjgl.opengl.GL11#GL_COLOR_ARRAY_TYPE
	 */
	val GL_COLOR_ARRAY_TYPE: Int = 32898

	/**
	 * Constant Value: 16384
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_COLOR_BUFFER_BIT
	 * @see org.lwjgl.opengl.GL11#GL_COLOR_BUFFER_BIT
	 */
	val GL_COLOR_BUFFER_BIT: Int = 16384

	/**
	 * Constant Value: 3106
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_COLOR_CLEAR_VALUE
	 * @see org.lwjgl.opengl.GL11#GL_COLOR_CLEAR_VALUE
	 */
	val GL_COLOR_CLEAR_VALUE: Int = 3106

	/**
	 * Constant Value: 3058
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_COLOR_LOGIC_OP
	 * @see org.lwjgl.opengl.GL11#GL_COLOR_LOGIC_OP
	 */
	val GL_COLOR_LOGIC_OP: Int = 3058

	/**
	 * Constant Value: 2903
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_COLOR_MATERIAL
	 * @see org.lwjgl.opengl.GL11#GL_COLOR_MATERIAL
	 */
	val GL_COLOR_MATERIAL: Int = 2903

	/**
	 * Constant Value: 3107
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_COLOR_WRITEMASK
	 * @see org.lwjgl.opengl.GL11#GL_COLOR_WRITEMASK
	 */
	val GL_COLOR_WRITEMASK: Int = 3107

	/**
	 * Constant Value: 34160
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_COMBINE
	 * @see org.lwjgl.opengl.GL13#GL_COMBINE
	 */
	val GL_COMBINE: Int = 34160

	/**
	 * Constant Value: 34162
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_COMBINE_ALPHA
	 * @see org.lwjgl.opengl.GL13#GL_COMBINE_ALPHA
	 */
	val GL_COMBINE_ALPHA: Int = 34162

	/**
	 * Constant Value: 34161
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_COMBINE_RGB
	 * @see org.lwjgl.opengl.GL13#GL_COMBINE_RGB
	 */
	val GL_COMBINE_RGB: Int = 34161

	/**
	 * Constant Value: 34467
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_COMPRESSED_TEXTURE_FORMATS
	 * @see org.lwjgl.opengl.GL13#GL_COMPRESSED_TEXTURE_FORMATS
	 */
	val GL_COMPRESSED_TEXTURE_FORMATS: Int = 34467

	/**
	 * Constant Value: 34166
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_CONSTANT
	 * @see org.lwjgl.opengl.GL13#GL_CONSTANT
	 */
	val GL_CONSTANT: Int = 34166

	/**
	 * Constant Value: 4615
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_CONSTANT_ATTENUATION
	 * @see org.lwjgl.opengl.GL11#GL_CONSTANT_ATTENUATION
	 */
	val GL_CONSTANT_ATTENUATION: Int = 4615

	/**
	 * Constant Value: 5379
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_COPY
	 * @see org.lwjgl.opengl.GL11#GL_COPY
	 */
	val GL_COPY: Int = 5379

	/**
	 * Constant Value: 5388
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_COPY_INVERTED
	 * @see org.lwjgl.opengl.GL11#GL_COPY_INVERTED
	 */
	val GL_COPY_INVERTED: Int = 5388

	/**
	 * Constant Value: 2884
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_CULL_FACE
	 * @see org.lwjgl.opengl.GL11#GL_CULL_FACE
	 */
	val GL_CULL_FACE: Int = 2884

	/**
	 * Constant Value: 2885
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_CULL_FACE_MODE
	 * @see org.lwjgl.opengl.GL11#GL_CULL_FACE_MODE
	 */
	val GL_CULL_FACE_MODE: Int = 2885

	/**
	 * Constant Value: 2816
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_CURRENT_COLOR
	 * @see org.lwjgl.opengl.GL11#GL_CURRENT_COLOR
	 */
	val GL_CURRENT_COLOR: Int = 2816

	/**
	 * Constant Value: 2818
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_CURRENT_NORMAL
	 * @see org.lwjgl.opengl.GL11#GL_CURRENT_NORMAL
	 */
	val GL_CURRENT_NORMAL: Int = 2818

	/**
	 * Constant Value: 2819
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_CURRENT_TEXTURE_COORDS
	 * @see org.lwjgl.opengl.GL11#GL_CURRENT_TEXTURE_COORDS
	 */
	val GL_CURRENT_TEXTURE_COORDS: Int = 2819

	/**
	 * Constant Value: 2304
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_CW
	 * @see org.lwjgl.opengl.GL11#GL_CW
	 */
	val GL_CW: Int = 2304

	/**
	 * Constant Value: 8449
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_DECAL
	 * @see org.lwjgl.opengl.GL11#GL_DECAL
	 */
	val GL_DECAL: Int = 8449

	/**
	 * Constant Value: 7683
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_DECR
	 * @see org.lwjgl.opengl.GL11#GL_DECR
	 */
	val GL_DECR: Int = 7683

	/**
	 * Constant Value: 3414
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_DEPTH_BITS
	 * @see org.lwjgl.opengl.GL11#GL_DEPTH_BITS
	 */
	val GL_DEPTH_BITS: Int = 3414

	/**
	 * Constant Value: 256
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_DEPTH_BUFFER_BIT
	 * @see org.lwjgl.opengl.GL11#GL_DEPTH_BUFFER_BIT
	 */
	val GL_DEPTH_BUFFER_BIT: Int = 256

	/**
	 * Constant Value: 2931
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_DEPTH_CLEAR_VALUE
	 * @see org.lwjgl.opengl.GL11#GL_DEPTH_CLEAR_VALUE
	 */
	val GL_DEPTH_CLEAR_VALUE: Int = 2931

	/**
	 * Constant Value: 2932
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_DEPTH_FUNC
	 * @see org.lwjgl.opengl.GL11#GL_DEPTH_FUNC
	 */
	val GL_DEPTH_FUNC: Int = 2932

	/**
	 * Constant Value: 2928
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_DEPTH_RANGE
	 * @see org.lwjgl.opengl.GL11#GL_DEPTH_RANGE
	 */
	val GL_DEPTH_RANGE: Int = 2928

	/**
	 * Constant Value: 2929
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_DEPTH_TEST
	 * @see org.lwjgl.opengl.GL11#GL_DEPTH_TEST
	 */
	val GL_DEPTH_TEST: Int = 2929

	/**
	 * Constant Value: 2930
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_DEPTH_WRITEMASK
	 * @see org.lwjgl.opengl.GL11#GL_DEPTH_WRITEMASK
	 */
	val GL_DEPTH_WRITEMASK: Int = 2930

	/**
	 * Constant Value: 4609
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_DIFFUSE
	 * @see org.lwjgl.opengl.GL11#GL_DIFFUSE
	 */
	val GL_DIFFUSE: Int = 4609

	/**
	 * Constant Value: 3024
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_DITHER
	 * @see org.lwjgl.opengl.GL11#GL_DITHER
	 */
	val GL_DITHER: Int = 3024

	/**
	 * Constant Value: 4352
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_DONT_CARE
	 * @see org.lwjgl.opengl.GL11#GL_DONT_CARE
	 */
	val GL_DONT_CARE: Int = 4352

	/**
	 * Constant Value: 34478
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_DOT3_RGB
	 * @see org.lwjgl.opengl.GL13#GL_DOT3_RGB
	 */
	val GL_DOT3_RGB: Int = 34478

	/**
	 * Constant Value: 34479
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_DOT3_RGBA
	 * @see org.lwjgl.opengl.GL13#GL_DOT3_RGBA
	 */
	val GL_DOT3_RGBA: Int = 34479

	/**
	 * Constant Value: 772
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_DST_ALPHA
	 * @see org.lwjgl.opengl.GL11#GL_DST_ALPHA
	 */
	val GL_DST_ALPHA: Int = 772

	/**
	 * Constant Value: 774
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_DST_COLOR
	 * @see org.lwjgl.opengl.GL11#GL_DST_COLOR
	 */
	val GL_DST_COLOR: Int = 774

	/**
	 * Constant Value: 35048
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_DYNAMIC_DRAW
	 * @see org.lwjgl.opengl.GL15#GL_DYNAMIC_DRAW
	 */
	val GL_DYNAMIC_DRAW: Int = 35048

	/**
	 * Constant Value: 34963
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_ELEMENT_ARRAY_BUFFER
	 * @see org.lwjgl.opengl.GL15#GL_ELEMENT_ARRAY_BUFFER
	 */
	val GL_ELEMENT_ARRAY_BUFFER: Int = 34963

	/**
	 * Constant Value: 34965
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_ELEMENT_ARRAY_BUFFER_BINDING
	 * @see org.lwjgl.opengl.GL15#GL_ELEMENT_ARRAY_BUFFER_BINDING
	 */
	val GL_ELEMENT_ARRAY_BUFFER_BINDING: Int = 34965

	/**
	 * Constant Value: 5632
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_EMISSION
	 * @see org.lwjgl.opengl.GL11#GL_EMISSION
	 */
	val GL_EMISSION: Int = 5632

	/**
	 * Constant Value: 514
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_EQUAL
	 * @see org.lwjgl.opengl.GL11#GL_EQUAL
	 */
	val GL_EQUAL: Int = 514

	/**
	 * Constant Value: 5385
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_EQUIV
	 * @see org.lwjgl.opengl.GL11#GL_EQUIV
	 */
	val GL_EQUIV: Int = 5385

	/**
	 * Constant Value: 2048
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_EXP
	 * @see org.lwjgl.opengl.GL11#GL_EXP
	 */
	val GL_EXP: Int = 2048

	/**
	 * Constant Value: 2049
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_EXP2
	 * @see org.lwjgl.opengl.GL11#GL_EXP2
	 */
	val GL_EXP2: Int = 2049

	/**
	 * Constant Value: 7939
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_EXTENSIONS
	 * @see org.lwjgl.opengl.GL11#GL_EXTENSIONS
	 */
	val GL_EXTENSIONS: Int = 7939

	/**
	 * Constant Value: 0
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FALSE
	 * @see org.lwjgl.opengl.GL11#GL_FALSE
	 */
	val GL_FALSE: Int = 0

	/**
	 * Constant Value: 4353
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FASTEST
	 * @see org.lwjgl.opengl.GL11#GL_FASTEST
	 */
	val GL_FASTEST: Int = 4353

	/**
	 * Constant Value: 5132
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FIXED
	 * @see org.lwjgl.opengl.GL41#GL_FIXED
	 */
	val GL_FIXED: Int = 5132

	/**
	 * Constant Value: 7424
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FLAT
	 * @see org.lwjgl.opengl.GL11#GL_FLAT
	 */
	val GL_FLAT: Int = 7424

	/**
	 * Constant Value: 5126
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FLOAT
	 * @see org.lwjgl.opengl.GL11#GL_FLOAT
	 */
	val GL_FLOAT: Int = 5126

	/**
	 * Constant Value: 2912
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FOG
	 * @see org.lwjgl.opengl.GL11#GL_FOG
	 */
	val GL_FOG: Int = 2912

	/**
	 * Constant Value: 2918
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FOG_COLOR
	 * @see org.lwjgl.opengl.GL11#GL_FOG_COLOR
	 */
	val GL_FOG_COLOR: Int = 2918

	/**
	 * Constant Value: 2914
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FOG_DENSITY
	 * @see org.lwjgl.opengl.GL11#GL_FOG_DENSITY
	 */
	val GL_FOG_DENSITY: Int = 2914

	/**
	 * Constant Value: 2916
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FOG_END
	 * @see org.lwjgl.opengl.GL11#GL_FOG_END
	 */
	val GL_FOG_END: Int = 2916

	/**
	 * Constant Value: 3156
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FOG_HINT
	 * @see org.lwjgl.opengl.GL11#GL_FOG_HINT
	 */
	val GL_FOG_HINT: Int = 3156

	/**
	 * Constant Value: 2917
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FOG_MODE
	 * @see org.lwjgl.opengl.GL11#GL_FOG_MODE
	 */
	val GL_FOG_MODE: Int = 2917

	/**
	 * Constant Value: 2915
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FOG_START
	 * @see org.lwjgl.opengl.GL11#GL_FOG_START
	 */
	val GL_FOG_START: Int = 2915

	/**
	 * Constant Value: 1028
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FRONT
	 * @see org.lwjgl.opengl.GL11#GL_FRONT
	 */
	val GL_FRONT: Int = 1028

	/**
	 * Constant Value: 1032
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_FRONT_AND_BACK
	 * @see org.lwjgl.opengl.GL11#GL_FRONT_AND_BACK
	 */
	val GL_FRONT_AND_BACK: Int = 1032

	/**
	 * Constant Value: 2886
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_FRONT_FACE
	 * @see org.lwjgl.opengl.GL11#GL_FRONT_FACE
	 */
	val GL_FRONT_FACE: Int = 2886

	/**
	 * Constant Value: 33169
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_GENERATE_MIPMAP
	 * @see org.lwjgl.opengl.GL14#GL_GENERATE_MIPMAP
	 */
	val GL_GENERATE_MIPMAP: Int = 33169

	/**
	 * Constant Value: 33170
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_GENERATE_MIPMAP_HINT
	 * @see org.lwjgl.opengl.GL14#GL_GENERATE_MIPMAP_HINT
	 */
	val GL_GENERATE_MIPMAP_HINT: Int = 33170

	/**
	 * Constant Value: 518
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_GEQUAL
	 * @see org.lwjgl.opengl.GL11#GL_GEQUAL
	 */
	val GL_GEQUAL: Int = 518

	/**
	 * Constant Value: 516
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_GREATER
	 * @see org.lwjgl.opengl.GL11#GL_GREATER
	 */
	val GL_GREATER: Int = 516

	/**
	 * Constant Value: 3411
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_GREEN_BITS
	 * @see org.lwjgl.opengl.GL11#GL_GREEN_BITS
	 */
	val GL_GREEN_BITS: Int = 3411

	/**
	 * Constant Value: 7682
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_INCR
	 * @see org.lwjgl.opengl.GL11#GL_INCR
	 */
	val GL_INCR: Int = 7682

	/**
	 * Constant Value: 34165
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_INTERPOLATE
	 * @see org.lwjgl.opengl.GL13#GL_INTERPOLATE
	 */
	val GL_INTERPOLATE: Int = 34165

	/**
	 * Constant Value: 1280
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_INVALID_ENUM
	 * @see org.lwjgl.opengl.GL11#GL_INVALID_ENUM
	 */
	val GL_INVALID_ENUM: Int = 1280

	/**
	 * Constant Value: 1282
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_INVALID_OPERATION
	 * @see org.lwjgl.opengl.GL11#GL_INVALID_OPERATION
	 */
	val GL_INVALID_OPERATION: Int = 1282

	/**
	 * Constant Value: 1281
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_INVALID_VALUE
	 * @see org.lwjgl.opengl.GL11#GL_INVALID_VALUE
	 */
	val GL_INVALID_VALUE: Int = 1281

	/**
	 * Constant Value: 5386
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_INVERT
	 * @see org.lwjgl.opengl.GL11#GL_INVERT
	 */
	val GL_INVERT: Int = 5386

	/**
	 * Constant Value: 7680
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_KEEP
	 * @see org.lwjgl.opengl.GL11#GL_KEEP
	 */
	val GL_KEEP: Int = 7680

	/**
	 * Constant Value: 515
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LEQUAL
	 * @see org.lwjgl.opengl.GL11#GL_LEQUAL
	 */
	val GL_LEQUAL: Int = 515

	/**
	 * Constant Value: 513
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LESS
	 * @see org.lwjgl.opengl.GL11#GL_LESS
	 */
	val GL_LESS: Int = 513

	/**
	 * Constant Value: 16384
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LIGHT0
	 * @see org.lwjgl.opengl.GL11#GL_LIGHT0
	 */
	val GL_LIGHT0: Int = 16384

	/**
	 * Constant Value: 16385
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LIGHT1
	 * @see org.lwjgl.opengl.GL11#GL_LIGHT1
	 */
	val GL_LIGHT1: Int = 16385

	/**
	 * Constant Value: 16386
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LIGHT2
	 * @see org.lwjgl.opengl.GL11#GL_LIGHT2
	 */
	val GL_LIGHT2: Int = 16386

	/**
	 * Constant Value: 16387
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LIGHT3
	 * @see org.lwjgl.opengl.GL11#GL_LIGHT3
	 */
	val GL_LIGHT3: Int = 16387

	/**
	 * Constant Value: 16388
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LIGHT4
	 * @see org.lwjgl.opengl.GL11#GL_LIGHT4
	 */
	val GL_LIGHT4: Int = 16388

	/**
	 * Constant Value: 16389
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LIGHT5
	 * @see org.lwjgl.opengl.GL11#GL_LIGHT5
	 */
	val GL_LIGHT5: Int = 16389

	/**
	 * Constant Value: 16390
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LIGHT6
	 * @see org.lwjgl.opengl.GL11#GL_LIGHT6
	 */
	val GL_LIGHT6: Int = 16390

	/**
	 * Constant Value: 16391
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LIGHT7
	 * @see org.lwjgl.opengl.GL11#GL_LIGHT7
	 */
	val GL_LIGHT7: Int = 16391

	/**
	 * Constant Value: 2896
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LIGHTING
	 * @see org.lwjgl.opengl.GL11#GL_LIGHTING
	 */
	val GL_LIGHTING: Int = 2896

	/**
	 * Constant Value: 2899
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LIGHT_MODEL_AMBIENT
	 * @see org.lwjgl.opengl.GL11#GL_LIGHT_MODEL_AMBIENT
	 */
	val GL_LIGHT_MODEL_AMBIENT: Int = 2899

	/**
	 * Constant Value: 2898
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LIGHT_MODEL_TWO_SIDE
	 * @see org.lwjgl.opengl.GL11#GL_LIGHT_MODEL_TWO_SIDE
	 */
	val GL_LIGHT_MODEL_TWO_SIDE: Int = 2898

	/**
	 * Constant Value: 9729
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LINEAR
	 * @see org.lwjgl.opengl.GL11#GL_LINEAR
	 */
	val GL_LINEAR: Int = 9729

	/**
	 * Constant Value: 4616
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LINEAR_ATTENUATION
	 * @see org.lwjgl.opengl.GL11#GL_LINEAR_ATTENUATION
	 */
	val GL_LINEAR_ATTENUATION: Int = 4616

	/**
	 * Constant Value: 9987
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LINEAR_MIPMAP_LINEAR
	 * @see org.lwjgl.opengl.GL11#GL_LINEAR_MIPMAP_LINEAR
	 */
	val GL_LINEAR_MIPMAP_LINEAR: Int = 9987

	/**
	 * Constant Value: 9985
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LINEAR_MIPMAP_NEAREST
	 * @see org.lwjgl.opengl.GL11#GL_LINEAR_MIPMAP_NEAREST
	 */
	val GL_LINEAR_MIPMAP_NEAREST: Int = 9985

	/**
	 * Constant Value: 1
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LINES
	 * @see org.lwjgl.opengl.GL11#GL_LINES
	 */
	val GL_LINES: Int = 1

	/**
	 * Constant Value: 2
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LINE_LOOP
	 * @see org.lwjgl.opengl.GL11#GL_LINE_LOOP
	 */
	val GL_LINE_LOOP: Int = 2

	/**
	 * Constant Value: 2848
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LINE_SMOOTH
	 * @see org.lwjgl.opengl.GL11#GL_LINE_SMOOTH
	 */
	val GL_LINE_SMOOTH: Int = 2848

	/**
	 * Constant Value: 3154
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LINE_SMOOTH_HINT
	 * @see org.lwjgl.opengl.GL11#GL_LINE_SMOOTH_HINT
	 */
	val GL_LINE_SMOOTH_HINT: Int = 3154

	/**
	 * Constant Value: 3
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LINE_STRIP
	 * @see org.lwjgl.opengl.GL11#GL_LINE_STRIP
	 */
	val GL_LINE_STRIP: Int = 3

	/**
	 * Constant Value: 2849
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_LINE_WIDTH
	 * @see org.lwjgl.opengl.GL11#GL_LINE_WIDTH
	 */
	val GL_LINE_WIDTH: Int = 2849

	/**
	 * Constant Value: 3056
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_LOGIC_OP_MODE
	 * @see org.lwjgl.opengl.GL11#GL_LOGIC_OP_MODE
	 */
	val GL_LOGIC_OP_MODE: Int = 3056

	/**
	 * Constant Value: 6409
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LUMINANCE
	 * @see org.lwjgl.opengl.GL11#GL_LUMINANCE
	 */
	val GL_LUMINANCE: Int = 6409

	/**
	 * Constant Value: 6410
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_LUMINANCE_ALPHA
	 * @see org.lwjgl.opengl.GL11#GL_LUMINANCE_ALPHA
	 */
	val GL_LUMINANCE_ALPHA: Int = 6410

	/**
	 * Constant Value: 2976
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_MATRIX_MODE
	 * @see org.lwjgl.opengl.GL11#GL_MATRIX_MODE
	 */
	val GL_MATRIX_MODE: Int = 2976

	/**
	 * Constant Value: 3378
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_MAX_CLIP_PLANES
	 * @see org.lwjgl.opengl.GL11#GL_MAX_CLIP_PLANES
	 */
	val GL_MAX_CLIP_PLANES: Int = 3378

	/**
	 * Constant Value: 33001
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_MAX_ELEMENTS_INDICES
	 * @see org.lwjgl.opengl.GL12#GL_MAX_ELEMENTS_INDICES
	 */
	val GL_MAX_ELEMENTS_INDICES: Int = 33001

	/**
	 * Constant Value: 33000
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_MAX_ELEMENTS_VERTICES
	 * @see org.lwjgl.opengl.GL12#GL_MAX_ELEMENTS_VERTICES
	 */
	val GL_MAX_ELEMENTS_VERTICES: Int = 33000

	/**
	 * Constant Value: 3377
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_MAX_LIGHTS
	 * @see org.lwjgl.opengl.GL11#GL_MAX_LIGHTS
	 */
	val GL_MAX_LIGHTS: Int = 3377

	/**
	 * Constant Value: 3382
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_MAX_MODELVIEW_STACK_DEPTH
	 * @see org.lwjgl.opengl.GL11#GL_MAX_MODELVIEW_STACK_DEPTH
	 */
	val GL_MAX_MODELVIEW_STACK_DEPTH: Int = 3382

	/**
	 * Constant Value: 3384
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_MAX_PROJECTION_STACK_DEPTH
	 * @see org.lwjgl.opengl.GL11#GL_MAX_PROJECTION_STACK_DEPTH
	 */
	val GL_MAX_PROJECTION_STACK_DEPTH: Int = 3384

	/**
	 * Constant Value: 3379
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_MAX_TEXTURE_SIZE
	 * @see org.lwjgl.opengl.GL11#GL_MAX_TEXTURE_SIZE
	 */
	val GL_MAX_TEXTURE_SIZE: Int = 3379

	/**
	 * Constant Value: 3385
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_MAX_TEXTURE_STACK_DEPTH
	 * @see org.lwjgl.opengl.GL11#GL_MAX_TEXTURE_STACK_DEPTH
	 */
	val GL_MAX_TEXTURE_STACK_DEPTH: Int = 3385

	/**
	 * Constant Value: 34018
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_MAX_TEXTURE_UNITS
	 * @see org.lwjgl.opengl.GL13#GL_MAX_TEXTURE_UNITS
	 */
	val GL_MAX_TEXTURE_UNITS: Int = 34018

	/**
	 * Constant Value: 3386
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_MAX_VIEWPORT_DIMS
	 * @see org.lwjgl.opengl.GL11#GL_MAX_VIEWPORT_DIMS
	 */
	val GL_MAX_VIEWPORT_DIMS: Int = 3386

	/**
	 * Constant Value: 5888
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_MODELVIEW
	 * @see org.lwjgl.opengl.GL11#GL_MODELVIEW
	 */
	val GL_MODELVIEW: Int = 5888

	/**
	 * Constant Value: 2982
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_MODELVIEW_MATRIX
	 * @see org.lwjgl.opengl.GL11#GL_MODELVIEW_MATRIX
	 */
	val GL_MODELVIEW_MATRIX: Int = 2982

	/**
	 * Constant Value: 2979
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_MODELVIEW_STACK_DEPTH
	 * @see org.lwjgl.opengl.GL11#GL_MODELVIEW_STACK_DEPTH
	 */
	val GL_MODELVIEW_STACK_DEPTH: Int = 2979

	/**
	 * Constant Value: 8448
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_MODULATE
	 * @see org.lwjgl.opengl.GL11#GL_MODULATE
	 */
	val GL_MODULATE: Int = 8448

	/**
	 * Constant Value: 32925
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_MULTISAMPLE
	 * @see org.lwjgl.opengl.GL13#GL_MULTISAMPLE
	 */
	val GL_MULTISAMPLE: Int = 32925

	/**
	 * Constant Value: 5390
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_NAND
	 * @see org.lwjgl.opengl.GL11#GL_NAND
	 */
	val GL_NAND: Int = 5390

	/**
	 * Constant Value: 9728
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_NEAREST
	 * @see org.lwjgl.opengl.GL11#GL_NEAREST
	 */
	val GL_NEAREST: Int = 9728

	/**
	 * Constant Value: 9986
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_NEAREST_MIPMAP_LINEAR
	 * @see org.lwjgl.opengl.GL11#GL_NEAREST_MIPMAP_LINEAR
	 */
	val GL_NEAREST_MIPMAP_LINEAR: Int = 9986

	/**
	 * Constant Value: 9984
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_NEAREST_MIPMAP_NEAREST
	 * @see org.lwjgl.opengl.GL11#GL_NEAREST_MIPMAP_NEAREST
	 */
	val GL_NEAREST_MIPMAP_NEAREST: Int = 9984

	/**
	 * Constant Value: 512
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_NEVER
	 * @see org.lwjgl.opengl.GL11#GL_NEVER
	 */
	val GL_NEVER: Int = 512

	/**
	 * Constant Value: 4354
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_NICEST
	 * @see org.lwjgl.opengl.GL11#GL_NICEST
	 */
	val GL_NICEST: Int = 4354

	/**
	 * Constant Value: 5381
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_NOOP
	 * @see org.lwjgl.opengl.GL11#GL_NOOP
	 */
	val GL_NOOP: Int = 5381

	/**
	 * Constant Value: 5384
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_NOR
	 * @see org.lwjgl.opengl.GL11#GL_NOR
	 */
	val GL_NOR: Int = 5384

	/**
	 * Constant Value: 2977
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_NORMALIZE
	 * @see org.lwjgl.opengl.GL11#GL_NORMALIZE
	 */
	val GL_NORMALIZE: Int = 2977

	/**
	 * Constant Value: 32885
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_NORMAL_ARRAY
	 * @see org.lwjgl.opengl.GL11#GL_NORMAL_ARRAY
	 */
	val GL_NORMAL_ARRAY: Int = 32885

	/**
	 * Constant Value: 34967
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_NORMAL_ARRAY_BUFFER_BINDING
	 * @see org.lwjgl.opengl.GL15#GL_NORMAL_ARRAY_BUFFER_BINDING
	 */
	val GL_NORMAL_ARRAY_BUFFER_BINDING: Int = 34967

	/**
	 * Constant Value: 32911
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_NORMAL_ARRAY_POINTER
	 * @see org.lwjgl.opengl.GL11#GL_NORMAL_ARRAY_POINTER
	 */
	val GL_NORMAL_ARRAY_POINTER: Int = 32911

	/**
	 * Constant Value: 32895
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_NORMAL_ARRAY_STRIDE
	 * @see org.lwjgl.opengl.GL11#GL_NORMAL_ARRAY_STRIDE
	 */
	val GL_NORMAL_ARRAY_STRIDE: Int = 32895

	/**
	 * Constant Value: 32894
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_NORMAL_ARRAY_TYPE
	 * @see org.lwjgl.opengl.GL11#GL_NORMAL_ARRAY_TYPE
	 */
	val GL_NORMAL_ARRAY_TYPE: Int = 32894

	/**
	 * Constant Value: 517
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_NOTEQUAL
	 * @see org.lwjgl.opengl.GL11#GL_NOTEQUAL
	 */
	val GL_NOTEQUAL: Int = 517

	/**
	 * Constant Value: 0
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_NO_ERROR
	 * @see org.lwjgl.opengl.GL11#GL_NO_ERROR
	 */
	val GL_NO_ERROR: Int = 0

	/**
	 * Constant Value: 34466
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_NUM_COMPRESSED_TEXTURE_FORMATS
	 * @see org.lwjgl.opengl.GL13#GL_NUM_COMPRESSED_TEXTURE_FORMATS
	 */
	val GL_NUM_COMPRESSED_TEXTURE_FORMATS: Int = 34466

	/**
	 * Constant Value: 1
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_ONE
	 * @see org.lwjgl.opengl.GL11#GL_ONE
	 */
	val GL_ONE: Int = 1

	/**
	 * Constant Value: 773
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_ONE_MINUS_DST_ALPHA
	 * @see org.lwjgl.opengl.GL11#GL_ONE_MINUS_DST_ALPHA
	 */
	val GL_ONE_MINUS_DST_ALPHA: Int = 773

	/**
	 * Constant Value: 775
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_ONE_MINUS_DST_COLOR
	 * @see org.lwjgl.opengl.GL11#GL_ONE_MINUS_DST_COLOR
	 */
	val GL_ONE_MINUS_DST_COLOR: Int = 775

	/**
	 * Constant Value: 771
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_ONE_MINUS_SRC_ALPHA
	 * @see org.lwjgl.opengl.GL11#GL_ONE_MINUS_SRC_ALPHA
	 */
	val GL_ONE_MINUS_SRC_ALPHA: Int = 771

	/**
	 * Constant Value: 769
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_ONE_MINUS_SRC_COLOR
	 * @see org.lwjgl.opengl.GL11#GL_ONE_MINUS_SRC_COLOR
	 */
	val GL_ONE_MINUS_SRC_COLOR: Int = 769

	/**
	 * Constant Value: 34200
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_OPERAND0_ALPHA
	 * @see org.lwjgl.opengl.GL13#GL_OPERAND0_ALPHA
	 */
	val GL_OPERAND0_ALPHA: Int = 34200

	/**
	 * Constant Value: 34192
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_OPERAND0_RGB
	 * @see org.lwjgl.opengl.GL13#GL_OPERAND0_RGB
	 */
	val GL_OPERAND0_RGB: Int = 34192

	/**
	 * Constant Value: 34201
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_OPERAND1_ALPHA
	 * @see org.lwjgl.opengl.GL13#GL_OPERAND1_ALPHA
	 */
	val GL_OPERAND1_ALPHA: Int = 34201

	/**
	 * Constant Value: 34193
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_OPERAND1_RGB
	 * @see org.lwjgl.opengl.GL13#GL_OPERAND1_RGB
	 */
	val GL_OPERAND1_RGB: Int = 34193

	/**
	 * Constant Value: 34202
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_OPERAND2_ALPHA
	 * @see org.lwjgl.opengl.GL13#GL_OPERAND2_ALPHA
	 */
	val GL_OPERAND2_ALPHA: Int = 34202

	/**
	 * Constant Value: 34194
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_OPERAND2_RGB
	 * @see org.lwjgl.opengl.GL13#GL_OPERAND2_RGB
	 */
	val GL_OPERAND2_RGB: Int = 34194

	/**
	 * Constant Value: 5383
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_OR
	 * @see org.lwjgl.opengl.GL11#GL_OR
	 */
	val GL_OR: Int = 5383

	/**
	 * Constant Value: 5389
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_OR_INVERTED
	 * @see org.lwjgl.opengl.GL11#GL_OR_INVERTED
	 */
	val GL_OR_INVERTED: Int = 5389

	/**
	 * Constant Value: 5387
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_OR_REVERSE
	 * @see org.lwjgl.opengl.GL11#GL_OR_REVERSE
	 */
	val GL_OR_REVERSE: Int = 5387

	/**
	 * Constant Value: 1285
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_OUT_OF_MEMORY
	 * @see org.lwjgl.opengl.GL11#GL_OUT_OF_MEMORY
	 */
	val GL_OUT_OF_MEMORY: Int = 1285

	/**
	 * Constant Value: 3333
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_PACK_ALIGNMENT
	 * @see org.lwjgl.opengl.GL11#GL_PACK_ALIGNMENT
	 */
	val GL_PACK_ALIGNMENT: Int = 3333

	/**
	 * Constant Value: 3152
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_PERSPECTIVE_CORRECTION_HINT
	 * @see org.lwjgl.opengl.GL11#GL_PERSPECTIVE_CORRECTION_HINT
	 */
	val GL_PERSPECTIVE_CORRECTION_HINT: Int = 3152

	/**
	 * Constant Value: 0
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_POINTS
	 * @see org.lwjgl.opengl.GL11#GL_POINTS
	 */
	val GL_POINTS: Int = 0

	/**
	 * Constant Value: 33065
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_POINT_DISTANCE_ATTENUATION
	 * @see org.lwjgl.opengl.GL14#GL_POINT_DISTANCE_ATTENUATION
	 */
	val GL_POINT_DISTANCE_ATTENUATION: Int = 33065

	/**
	 * Constant Value: 33064
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_POINT_FADE_THRESHOLD_SIZE
	 * @see org.lwjgl.opengl.GL14#GL_POINT_FADE_THRESHOLD_SIZE
	 */
	val GL_POINT_FADE_THRESHOLD_SIZE: Int = 33064

	/**
	 * Constant Value: 2833
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_POINT_SIZE
	 * @see org.lwjgl.opengl.GL11#GL_POINT_SIZE
	 */
	val GL_POINT_SIZE: Int = 2833

	/**
	 * Constant Value: 33063
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_POINT_SIZE_MAX
	 * @see org.lwjgl.opengl.GL14#GL_POINT_SIZE_MAX
	 */
	val GL_POINT_SIZE_MAX: Int = 33063

	/**
	 * Constant Value: 33062
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_POINT_SIZE_MIN
	 * @see org.lwjgl.opengl.GL14#GL_POINT_SIZE_MIN
	 */
	val GL_POINT_SIZE_MIN: Int = 33062

	/**
	 * Constant Value: 2832
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_POINT_SMOOTH
	 * @see org.lwjgl.opengl.GL11#GL_POINT_SMOOTH
	 */
	val GL_POINT_SMOOTH: Int = 2832

	/**
	 * Constant Value: 3153
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_POINT_SMOOTH_HINT
	 * @see org.lwjgl.opengl.GL11#GL_POINT_SMOOTH_HINT
	 */
	val GL_POINT_SMOOTH_HINT: Int = 3153

	/**
	 * Constant Value: 32824
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_POLYGON_OFFSET_FACTOR
	 * @see org.lwjgl.opengl.GL11#GL_POLYGON_OFFSET_FACTOR
	 */
	val GL_POLYGON_OFFSET_FACTOR: Int = 32824

	/**
	 * Constant Value: 32823
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_POLYGON_OFFSET_FILL
	 * @see org.lwjgl.opengl.GL11#GL_POLYGON_OFFSET_FILL
	 */
	val GL_POLYGON_OFFSET_FILL: Int = 32823

	/**
	 * Constant Value: 10752
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_POLYGON_OFFSET_UNITS
	 * @see org.lwjgl.opengl.GL11#GL_POLYGON_OFFSET_UNITS
	 */
	val GL_POLYGON_OFFSET_UNITS: Int = 10752

	/**
	 * Constant Value: 3155
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_POLYGON_SMOOTH_HINT
	 * @see org.lwjgl.opengl.GL11#GL_POLYGON_SMOOTH_HINT
	 */
	val GL_POLYGON_SMOOTH_HINT: Int = 3155

	/**
	 * Constant Value: 4611
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_POSITION
	 * @see org.lwjgl.opengl.GL11#GL_POSITION
	 */
	val GL_POSITION: Int = 4611

	/**
	 * Constant Value: 34168
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_PREVIOUS
	 * @see org.lwjgl.opengl.GL13#GL_PREVIOUS
	 */
	val GL_PREVIOUS: Int = 34168

	/**
	 * Constant Value: 34167
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_PRIMARY_COLOR
	 * @see org.lwjgl.opengl.GL13#GL_PRIMARY_COLOR
	 */
	val GL_PRIMARY_COLOR: Int = 34167

	/**
	 * Constant Value: 5889
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_PROJECTION
	 * @see org.lwjgl.opengl.GL11#GL_PROJECTION
	 */
	val GL_PROJECTION: Int = 5889

	/**
	 * Constant Value: 2983
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_PROJECTION_MATRIX
	 * @see org.lwjgl.opengl.GL11#GL_PROJECTION_MATRIX
	 */
	val GL_PROJECTION_MATRIX: Int = 2983

	/**
	 * Constant Value: 2980
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_PROJECTION_STACK_DEPTH
	 * @see org.lwjgl.opengl.GL11#GL_PROJECTION_STACK_DEPTH
	 */
	val GL_PROJECTION_STACK_DEPTH: Int = 2980

	/**
	 * Constant Value: 4617
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_QUADRATIC_ATTENUATION
	 * @see org.lwjgl.opengl.GL11#GL_QUADRATIC_ATTENUATION
	 */
	val GL_QUADRATIC_ATTENUATION: Int = 4617

	/**
	 * Constant Value: 3410
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_RED_BITS
	 * @see org.lwjgl.opengl.GL11#GL_RED_BITS
	 */
	val GL_RED_BITS: Int = 3410

	/**
	 * Constant Value: 7937
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_RENDERER
	 * @see org.lwjgl.opengl.GL11#GL_RENDERER
	 */
	val GL_RENDERER: Int = 7937

	/**
	 * Constant Value: 10497
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_REPEAT
	 * @see org.lwjgl.opengl.GL11#GL_REPEAT
	 */
	val GL_REPEAT: Int = 10497

	/**
	 * Constant Value: 7681
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_REPLACE
	 * @see org.lwjgl.opengl.GL11#GL_REPLACE
	 */
	val GL_REPLACE: Int = 7681

	/**
	 * Constant Value: 32826
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_RESCALE_NORMAL
	 * @see org.lwjgl.opengl.GL12#GL_RESCALE_NORMAL
	 */
	val GL_RESCALE_NORMAL: Int = 32826

	/**
	 * Constant Value: 6407
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_RGB
	 * @see org.lwjgl.opengl.GL11#GL_RGB
	 */
	val GL_RGB: Int = 6407

	/**
	 * Constant Value: 6408
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_RGBA
	 * @see org.lwjgl.opengl.GL11#GL_RGBA
	 */
	val GL_RGBA: Int = 6408

	/**
	 * Constant Value: 34163
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_RGB_SCALE
	 * @see org.lwjgl.opengl.GL13#GL_RGB_SCALE
	 */
	val GL_RGB_SCALE: Int = 34163

	/**
	 * Constant Value: 32937
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_SAMPLES
	 * @see org.lwjgl.opengl.GL13#GL_SAMPLES
	 */
	val GL_SAMPLES: Int = 32937

	/**
	 * Constant Value: 32926
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SAMPLE_ALPHA_TO_COVERAGE
	 * @see org.lwjgl.opengl.GL13#GL_SAMPLE_ALPHA_TO_COVERAGE
	 */
	val GL_SAMPLE_ALPHA_TO_COVERAGE: Int = 32926

	/**
	 * Constant Value: 32927
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SAMPLE_ALPHA_TO_ONE
	 * @see org.lwjgl.opengl.GL13#GL_SAMPLE_ALPHA_TO_ONE
	 */
	val GL_SAMPLE_ALPHA_TO_ONE: Int = 32927

	/**
	 * Constant Value: 32936
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_SAMPLE_BUFFERS
	 * @see org.lwjgl.opengl.GL13#GL_SAMPLE_BUFFERS
	 */
	val GL_SAMPLE_BUFFERS: Int = 32936

	/**
	 * Constant Value: 32928
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SAMPLE_COVERAGE
	 * @see org.lwjgl.opengl.GL13#GL_SAMPLE_COVERAGE
	 */
	val GL_SAMPLE_COVERAGE: Int = 32928

	/**
	 * Constant Value: 32939
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_SAMPLE_COVERAGE_INVERT
	 * @see org.lwjgl.opengl.GL13#GL_SAMPLE_COVERAGE_INVERT
	 */
	val GL_SAMPLE_COVERAGE_INVERT: Int = 32939

	/**
	 * Constant Value: 32938
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_SAMPLE_COVERAGE_VALUE
	 * @see org.lwjgl.opengl.GL13#GL_SAMPLE_COVERAGE_VALUE
	 */
	val GL_SAMPLE_COVERAGE_VALUE: Int = 32938

	/**
	 * Constant Value: 3088
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_SCISSOR_BOX
	 * @see org.lwjgl.opengl.GL11#GL_SCISSOR_BOX
	 */
	val GL_SCISSOR_BOX: Int = 3088

	/**
	 * Constant Value: 3089
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SCISSOR_TEST
	 * @see org.lwjgl.opengl.GL11#GL_SCISSOR_TEST
	 */
	val GL_SCISSOR_TEST: Int = 3089

	/**
	 * Constant Value: 5391
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SET
	 * @see org.lwjgl.opengl.GL11#GL_SET
	 */
	val GL_SET: Int = 5391

	/**
	 * Constant Value: 2900
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_SHADE_MODEL
	 * @see org.lwjgl.opengl.GL11#GL_SHADE_MODEL
	 */
	val GL_SHADE_MODEL: Int = 2900

	/**
	 * Constant Value: 5633
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SHININESS
	 * @see org.lwjgl.opengl.GL11#GL_SHININESS
	 */
	val GL_SHININESS: Int = 5633

	/**
	 * Constant Value: 5122
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SHORT
	 * @see org.lwjgl.opengl.GL11#GL_SHORT
	 */
	val GL_SHORT: Int = 5122

	/**
	 * Constant Value: 7425
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SMOOTH
	 * @see org.lwjgl.opengl.GL11#GL_SMOOTH
	 */
	val GL_SMOOTH: Int = 7425

	/**
	 * Constant Value: 2850
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SMOOTH_LINE_WIDTH_RANGE
	 * @see org.lwjgl.opengl.GL12#GL_SMOOTH_LINE_WIDTH_RANGE
	 */
	val GL_SMOOTH_LINE_WIDTH_RANGE: Int = 2850

	/**
	 * Constant Value: 2834
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SMOOTH_POINT_SIZE_RANGE
	 * @see org.lwjgl.opengl.GL12#GL_SMOOTH_POINT_SIZE_RANGE
	 */
	val GL_SMOOTH_POINT_SIZE_RANGE: Int = 2834

	/**
	 * Constant Value: 4610
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SPECULAR
	 * @see org.lwjgl.opengl.GL11#GL_SPECULAR
	 */
	val GL_SPECULAR: Int = 4610

	/**
	 * Constant Value: 4614
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SPOT_CUTOFF
	 * @see org.lwjgl.opengl.GL11#GL_SPOT_CUTOFF
	 */
	val GL_SPOT_CUTOFF: Int = 4614

	/**
	 * Constant Value: 4612
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SPOT_DIRECTION
	 * @see org.lwjgl.opengl.GL11#GL_SPOT_DIRECTION
	 */
	val GL_SPOT_DIRECTION: Int = 4612

	/**
	 * Constant Value: 4613
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SPOT_EXPONENT
	 * @see org.lwjgl.opengl.GL11#GL_SPOT_EXPONENT
	 */
	val GL_SPOT_EXPONENT: Int = 4613

	/**
	 * Constant Value: 34184
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_SRC0_ALPHA
	 * @see org.lwjgl.opengl.GL15#GL_SRC0_ALPHA
	 */
	val GL_SRC0_ALPHA: Int = 34184

	/**
	 * Constant Value: 34176
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_SRC0_RGB
	 * @see org.lwjgl.opengl.GL15#GL_SRC0_RGB
	 */
	val GL_SRC0_RGB: Int = 34176

	/**
	 * Constant Value: 34185
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_SRC1_ALPHA
	 * @see org.lwjgl.opengl.GL15#GL_SRC1_ALPHA
	 */
	val GL_SRC1_ALPHA: Int = 34185

	/**
	 * Constant Value: 34177
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_SRC1_RGB
	 * @see org.lwjgl.opengl.GL15#GL_SRC1_RGB
	 */
	val GL_SRC1_RGB: Int = 34177

	/**
	 * Constant Value: 34186
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_SRC2_ALPHA
	 * @see org.lwjgl.opengl.GL15#GL_SRC2_ALPHA
	 */
	val GL_SRC2_ALPHA: Int = 34186

	/**
	 * Constant Value: 34178
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_SRC2_RGB
	 * @see org.lwjgl.opengl.GL15#GL_SRC2_RGB
	 */
	val GL_SRC2_RGB: Int = 34178

	/**
	 * Constant Value: 770
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SRC_ALPHA
	 * @see org.lwjgl.opengl.GL11#GL_SRC_ALPHA
	 */
	val GL_SRC_ALPHA: Int = 770

	/**
	 * Constant Value: 776
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SRC_ALPHA_SATURATE
	 * @see org.lwjgl.opengl.GL11#GL_SRC_ALPHA_SATURATE
	 */
	val GL_SRC_ALPHA_SATURATE: Int = 776

	/**
	 * Constant Value: 768
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SRC_COLOR
	 * @see org.lwjgl.opengl.GL11#GL_SRC_COLOR
	 */
	val GL_SRC_COLOR: Int = 768

	/**
	 * Constant Value: 1283
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_STACK_OVERFLOW
	 * @see org.lwjgl.opengl.GL11#GL_STACK_OVERFLOW
	 */
	val GL_STACK_OVERFLOW: Int = 1283

	/**
	 * Constant Value: 1284
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_STACK_UNDERFLOW
	 * @see org.lwjgl.opengl.GL11#GL_STACK_UNDERFLOW
	 */
	val GL_STACK_UNDERFLOW: Int = 1284

	/**
	 * Constant Value: 35044
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_STATIC_DRAW
	 * @see org.lwjgl.opengl.GL15#GL_STATIC_DRAW
	 */
	val GL_STATIC_DRAW: Int = 35044

	/**
	 * Constant Value: 3415
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_STENCIL_BITS
	 * @see org.lwjgl.opengl.GL11#GL_STENCIL_BITS
	 */
	val GL_STENCIL_BITS: Int = 3415

	/**
	 * Constant Value: 1024
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_STENCIL_BUFFER_BIT
	 * @see org.lwjgl.opengl.GL11#GL_STENCIL_BUFFER_BIT
	 */
	val GL_STENCIL_BUFFER_BIT: Int = 1024

	/**
	 * Constant Value: 2961
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_STENCIL_CLEAR_VALUE
	 * @see org.lwjgl.opengl.GL11#GL_STENCIL_CLEAR_VALUE
	 */
	val GL_STENCIL_CLEAR_VALUE: Int = 2961

	/**
	 * Constant Value: 2964
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_STENCIL_FAIL
	 * @see org.lwjgl.opengl.GL11#GL_STENCIL_FAIL
	 */
	val GL_STENCIL_FAIL: Int = 2964

	/**
	 * Constant Value: 2962
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_STENCIL_FUNC
	 * @see org.lwjgl.opengl.GL11#GL_STENCIL_FUNC
	 */
	val GL_STENCIL_FUNC: Int = 2962

	/**
	 * Constant Value: 2965
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_STENCIL_PASS_DEPTH_FAIL
	 * @see org.lwjgl.opengl.GL11#GL_STENCIL_PASS_DEPTH_FAIL
	 */
	val GL_STENCIL_PASS_DEPTH_FAIL: Int = 2965

	/**
	 * Constant Value: 2966
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_STENCIL_PASS_DEPTH_PASS
	 * @see org.lwjgl.opengl.GL11#GL_STENCIL_PASS_DEPTH_PASS
	 */
	val GL_STENCIL_PASS_DEPTH_PASS: Int = 2966

	/**
	 * Constant Value: 2967
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_STENCIL_REF
	 * @see org.lwjgl.opengl.GL11#GL_STENCIL_REF
	 */
	val GL_STENCIL_REF: Int = 2967

	/**
	 * Constant Value: 2960
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_STENCIL_TEST
	 * @see org.lwjgl.opengl.GL11#GL_STENCIL_TEST
	 */
	val GL_STENCIL_TEST: Int = 2960

	/**
	 * Constant Value: 2963
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_STENCIL_VALUE_MASK
	 * @see org.lwjgl.opengl.GL11#GL_STENCIL_VALUE_MASK
	 */
	val GL_STENCIL_VALUE_MASK: Int = 2963

	/**
	 * Constant Value: 2968
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_STENCIL_WRITEMASK
	 * @see org.lwjgl.opengl.GL11#GL_STENCIL_WRITEMASK
	 */
	val GL_STENCIL_WRITEMASK: Int = 2968

	/**
	 * Constant Value: 3408
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_SUBPIXEL_BITS
	 * @see org.lwjgl.opengl.GL11#GL_SUBPIXEL_BITS
	 */
	val GL_SUBPIXEL_BITS: Int = 3408

	/**
	 * Constant Value: 34023
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_SUBTRACT
	 * @see org.lwjgl.opengl.GL13#GL_SUBTRACT
	 */
	val GL_SUBTRACT: Int = 34023

	/**
	 * Constant Value: 5890
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE
	 */
	val GL_TEXTURE: Int = 5890

	/**
	 * Constant Value: 33984
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE0
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE0
	 */
	val GL_TEXTURE0: Int = 33984

	/**
	 * Constant Value: 33985
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE1
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE1
	 */
	val GL_TEXTURE1: Int = 33985

	/**
	 * Constant Value: 33994
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE10
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE10
	 */
	val GL_TEXTURE10: Int = 33994

	/**
	 * Constant Value: 33995
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE11
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE11
	 */
	val GL_TEXTURE11: Int = 33995

	/**
	 * Constant Value: 33996
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE12
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE12
	 */
	val GL_TEXTURE12: Int = 33996

	/**
	 * Constant Value: 33997
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE13
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE13
	 */
	val GL_TEXTURE13: Int = 33997

	/**
	 * Constant Value: 33998
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE14
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE14
	 */
	val GL_TEXTURE14: Int = 33998

	/**
	 * Constant Value: 33999
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE15
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE15
	 */
	val GL_TEXTURE15: Int = 33999

	/**
	 * Constant Value: 34000
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE16
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE16
	 */
	val GL_TEXTURE16: Int = 34000

	/**
	 * Constant Value: 34001
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE17
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE17
	 */
	val GL_TEXTURE17: Int = 34001

	/**
	 * Constant Value: 34002
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE18
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE18
	 */
	val GL_TEXTURE18: Int = 34002

	/**
	 * Constant Value: 34003
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE19
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE19
	 */
	val GL_TEXTURE19: Int = 34003

	/**
	 * Constant Value: 33986
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE2
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE2
	 */
	val GL_TEXTURE2: Int = 33986

	/**
	 * Constant Value: 34004
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE20
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE20
	 */
	val GL_TEXTURE20: Int = 34004

	/**
	 * Constant Value: 34005
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE21
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE21
	 */
	val GL_TEXTURE21: Int = 34005

	/**
	 * Constant Value: 34006
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE22
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE22
	 */
	val GL_TEXTURE22: Int = 34006

	/**
	 * Constant Value: 34007
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE23
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE23
	 */
	val GL_TEXTURE23: Int = 34007

	/**
	 * Constant Value: 34008
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE24
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE24
	 */
	val GL_TEXTURE24: Int = 34008

	/**
	 * Constant Value: 34009
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE25
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE25
	 */
	val GL_TEXTURE25: Int = 34009

	/**
	 * Constant Value: 34010
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE26
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE26
	 */
	val GL_TEXTURE26: Int = 34010

	/**
	 * Constant Value: 34011
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE27
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE27
	 */
	val GL_TEXTURE27: Int = 34011

	/**
	 * Constant Value: 34012
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE28
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE28
	 */
	val GL_TEXTURE28: Int = 34012

	/**
	 * Constant Value: 34013
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE29
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE29
	 */
	val GL_TEXTURE29: Int = 34013

	/**
	 * Constant Value: 33987
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE3
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE3
	 */
	val GL_TEXTURE3: Int = 33987

	/**
	 * Constant Value: 34014
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE30
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE30
	 */
	val GL_TEXTURE30: Int = 34014

	/**
	 * Constant Value: 34015
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE31
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE31
	 */
	val GL_TEXTURE31: Int = 34015

	/**
	 * Constant Value: 33988
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE4
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE4
	 */
	val GL_TEXTURE4: Int = 33988

	/**
	 * Constant Value: 33989
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE5
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE5
	 */
	val GL_TEXTURE5: Int = 33989

	/**
	 * Constant Value: 33990
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE6
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE6
	 */
	val GL_TEXTURE6: Int = 33990

	/**
	 * Constant Value: 33991
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE7
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE7
	 */
	val GL_TEXTURE7: Int = 33991

	/**
	 * Constant Value: 33992
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE8
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE8
	 */
	val GL_TEXTURE8: Int = 33992

	/**
	 * Constant Value: 33993
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE9
	 * @see org.lwjgl.opengl.GL13#GL_TEXTURE9
	 */
	val GL_TEXTURE9: Int = 33993

	/**
	 * Constant Value: 3553
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE_2D
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_2D
	 */
	val GL_TEXTURE_2D: Int = 3553

	/**
	 * Constant Value: 32873
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_TEXTURE_BINDING_2D
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_BINDING_2D
	 */
	val GL_TEXTURE_BINDING_2D: Int = 32873

	/**
	 * Constant Value: 32888
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE_COORD_ARRAY
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_COORD_ARRAY
	 */
	val GL_TEXTURE_COORD_ARRAY: Int = 32888

	/**
	 * Constant Value: 34970
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING
	 * @see org.lwjgl.opengl.GL15#GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING
	 */
	val GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING: Int = 34970

	/**
	 * Constant Value: 32914
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_TEXTURE_COORD_ARRAY_POINTER
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_COORD_ARRAY_POINTER
	 */
	val GL_TEXTURE_COORD_ARRAY_POINTER: Int = 32914

	/**
	 * Constant Value: 32904
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_TEXTURE_COORD_ARRAY_SIZE
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_COORD_ARRAY_SIZE
	 */
	val GL_TEXTURE_COORD_ARRAY_SIZE: Int = 32904

	/**
	 * Constant Value: 32906
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_TEXTURE_COORD_ARRAY_STRIDE
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_COORD_ARRAY_STRIDE
	 */
	val GL_TEXTURE_COORD_ARRAY_STRIDE: Int = 32906

	/**
	 * Constant Value: 32905
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_TEXTURE_COORD_ARRAY_TYPE
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_COORD_ARRAY_TYPE
	 */
	val GL_TEXTURE_COORD_ARRAY_TYPE: Int = 32905

	/**
	 * Constant Value: 8960
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE_ENV
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_ENV
	 */
	val GL_TEXTURE_ENV: Int = 8960

	/**
	 * Constant Value: 8705
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE_ENV_COLOR
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_ENV_COLOR
	 */
	val GL_TEXTURE_ENV_COLOR: Int = 8705

	/**
	 * Constant Value: 8704
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE_ENV_MODE
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_ENV_MODE
	 */
	val GL_TEXTURE_ENV_MODE: Int = 8704

	/**
	 * Constant Value: 10240
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE_MAG_FILTER
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_MAG_FILTER
	 */
	val GL_TEXTURE_MAG_FILTER: Int = 10240

	/**
	 * Constant Value: 2984
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_TEXTURE_MATRIX
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_MATRIX
	 */
	val GL_TEXTURE_MATRIX: Int = 2984

	/**
	 * Constant Value: 10241
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE_MIN_FILTER
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_MIN_FILTER
	 */
	val GL_TEXTURE_MIN_FILTER: Int = 10241

	/**
	 * Constant Value: 2981
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_TEXTURE_STACK_DEPTH
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_STACK_DEPTH
	 */
	val GL_TEXTURE_STACK_DEPTH: Int = 2981

	/**
	 * Constant Value: 10242
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE_WRAP_S
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_WRAP_S
	 */
	val GL_TEXTURE_WRAP_S: Int = 10242

	/**
	 * Constant Value: 10243
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TEXTURE_WRAP_T
	 * @see org.lwjgl.opengl.GL11#GL_TEXTURE_WRAP_T
	 */
	val GL_TEXTURE_WRAP_T: Int = 10243

	/**
	 * Constant Value: 4
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TRIANGLES
	 * @see org.lwjgl.opengl.GL11#GL_TRIANGLES
	 */
	val GL_TRIANGLES: Int = 4

	/**
	 * Constant Value: 6
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TRIANGLE_FAN
	 * @see org.lwjgl.opengl.GL11#GL_TRIANGLE_FAN
	 */
	val GL_TRIANGLE_FAN: Int = 6

	/**
	 * Constant Value: 5
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TRIANGLE_STRIP
	 * @see org.lwjgl.opengl.GL11#GL_TRIANGLE_STRIP
	 */
	val GL_TRIANGLE_STRIP: Int = 5

	/**
	 * Constant Value: 1
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_TRUE
	 * @see org.lwjgl.opengl.GL11#GL_TRUE
	 */
	val GL_TRUE: Int = 1

	/**
	 * Constant Value: 3317
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_UNPACK_ALIGNMENT
	 * @see org.lwjgl.opengl.GL11#GL_UNPACK_ALIGNMENT
	 */
	val GL_UNPACK_ALIGNMENT: Int = 3317

	/**
	 * Constant Value: 5121
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_UNSIGNED_BYTE
	 * @see org.lwjgl.opengl.GL11#GL_UNSIGNED_BYTE
	 */
	val GL_UNSIGNED_BYTE: Int = 5121

	/**
	 * Constant Value: 5123
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_UNSIGNED_SHORT
	 * @see org.lwjgl.opengl.GL11#GL_UNSIGNED_SHORT
	 */
	val GL_UNSIGNED_SHORT: Int = 5123

	/**
	 * Constant Value: 32819
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_UNSIGNED_SHORT_4_4_4_4
	 * @see org.lwjgl.opengl.GL12#GL_UNSIGNED_SHORT_4_4_4_4
	 */
	val GL_UNSIGNED_SHORT_4_4_4_4: Int = 32819

	/**
	 * Constant Value: 32820
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_UNSIGNED_SHORT_5_5_5_1
	 * @see org.lwjgl.opengl.GL12#GL_UNSIGNED_SHORT_5_5_5_1
	 */
	val GL_UNSIGNED_SHORT_5_5_5_1: Int = 32820

	/**
	 * Constant Value: 33635
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_UNSIGNED_SHORT_5_6_5
	 * @see org.lwjgl.opengl.GL12#GL_UNSIGNED_SHORT_5_6_5
	 */
	val GL_UNSIGNED_SHORT_5_6_5: Int = 33635

	/**
	 * Constant Value: 7936
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_VENDOR
	 * @see org.lwjgl.opengl.GL11#GL_VENDOR
	 */
	val GL_VENDOR: Int = 7936

	/**
	 * Constant Value: 7938
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_VERSION
	 * @see org.lwjgl.opengl.GL11#GL_VERSION
	 */
	val GL_VERSION: Int = 7938

	/**
	 * Constant Value: 32884
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_VERTEX_ARRAY
	 * @see org.lwjgl.opengl.GL11#GL_VERTEX_ARRAY
	 */
	val GL_VERTEX_ARRAY: Int = 32884

	/**
	 * Constant Value: 34966
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_VERTEX_ARRAY_BUFFER_BINDING
	 * @see org.lwjgl.opengl.GL15#GL_VERTEX_ARRAY_BUFFER_BINDING
	 */
	val GL_VERTEX_ARRAY_BUFFER_BINDING: Int = 34966

	/**
	 * Constant Value: 32910
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_VERTEX_ARRAY_POINTER
	 * @see org.lwjgl.opengl.GL11#GL_VERTEX_ARRAY_POINTER
	 */
	val GL_VERTEX_ARRAY_POINTER: Int = 32910

	/**
	 * Constant Value: 32890
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_VERTEX_ARRAY_SIZE
	 * @see org.lwjgl.opengl.GL11#GL_VERTEX_ARRAY_SIZE
	 */
	val GL_VERTEX_ARRAY_SIZE: Int = 32890

	/**
	 * Constant Value: 32892
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_VERTEX_ARRAY_STRIDE
	 * @see org.lwjgl.opengl.GL11#GL_VERTEX_ARRAY_STRIDE
	 */
	val GL_VERTEX_ARRAY_STRIDE: Int = 32892

	/**
	 * Constant Value: 32891
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_VERTEX_ARRAY_TYPE
	 * @see org.lwjgl.opengl.GL11#GL_VERTEX_ARRAY_TYPE
	 */
	val GL_VERTEX_ARRAY_TYPE: Int = 32891

	/**
	 * Constant Value: 2978
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_VIEWPORT
	 * @see org.lwjgl.opengl.GL11#GL_VIEWPORT
	 */
	val GL_VIEWPORT: Int = 2978

	/**
	 * Constant Value: 35001
	 * 
	 * @see javax.microedition.khronos.opengles.GL11#GL_WRITE_ONLY
	 * @see org.lwjgl.opengl.GL15#GL_WRITE_ONLY
	 */
	val GL_WRITE_ONLY: Int = 35001

	/**
	 * Constant Value: 5382
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_XOR
	 * @see org.lwjgl.opengl.GL11#GL_XOR
	 */
	val GL_XOR: Int = 5382

	/**
	 * Constant Value: 0
	 * 
	 * @see javax.microedition.khronos.opengles.GL10#GL_ZERO
	 * @see org.lwjgl.opengl.GL11#GL_ZERO
	 */
	val GL_ZERO: Int = 0

	def glActiveTexture(): Unit = {
	}

	def glAlphaFunc(): Unit = {
	}

	def glBindBuffer(): Unit = {
	}

	def glBindTexture(): Unit = {
	}

	def glBlendFunc(): Unit = {
	}

	def glBufferData(): Unit = {
	}

	def glBufferSubData(): Unit = {
	}

	def glClear(): Unit = {
	}

	def glClearColor(): Unit = {
	}

	def glClearDepth(): Unit = {
	}

	def glClearStencil(): Unit = {
	}

	def glClientActiveTexture(): Unit = {
	}

	def glClipPlane(): Unit = {
	}

	def glColor(): Unit = {
	}

	def glColorMask(): Unit = {
	}

	def glColorPointer(): Unit = {
	}

	def glCompressedTexImage2D(): Unit = {
	}

	def glCompressedTexSubImage2D(): Unit = {
	}

	def glCopyTexImage2D(): Unit = {
	}

	def glCopyTexSubImage2D(): Unit = {
	}

	def glCullFace(): Unit = {
	}

	def glDeleteBuffers(): Unit = {
	}

	def glDeleteTextures(): Unit = {
	}

	def glDepthFunc(): Unit = {
	}

	def glDepthMask(): Unit = {
	}

	def glDepthRange(): Unit = {
	}

	def glDisable(): Unit = {
	}

	def glDisableClientState(): Unit = {
	}

	def glDrawArrays(): Unit = {
	}

	def glDrawElements(): Unit = {
	}

	def glEnable(): Unit = {
	}

	def glEnableClientState(): Unit = {
	}

	def glFinish(): Unit = {
	}

	def glFlush(): Unit = {
	}

	def glFog(): Unit = {
	}

	def glFrontFace(): Unit = {
	}

	def glFrustum(): Unit = {
	}

	def glGenBuffers(): Unit = {
	}

	def glGenTextures(): Unit = {
	}

	def glGetClipPlane(): Unit = {
	}

	def glGetError(): Unit = {
	}

	def glGetLight(): Unit = {
	}

	def glGetMaterial(): Unit = {
	}

	def glGetString(): Unit = {
	}

	def glGetTexEnv(): Unit = {
	}

	def glGetTexParameter(): Unit = {
	}

	def glHint(): Unit = {
	}

	def glIsBuffer(): Unit = {
	}

	def glIsEnabled(): Unit = {
	}

	def glIsTexture(): Unit = {
	}

	def glLight(): Unit = {
	}

	def glLightModel(): Unit = {
	}

	def glLineWidth(): Unit = {
	}

	def glLoadIdentity(): Unit = {
	}

	def glLoadMatrix(): Unit = {
	}

	def glLogicOp(): Unit = {
	}

	def glMaterial(): Unit = {
	}

	def glMatrixMode(): Unit = {
	}

	def glMultMatrix(): Unit = {
	}

	def glMultiTexCoord(): Unit = {
	}

	def glNormal(): Unit = {
	}

	def glNormalPointer(): Unit = {
	}

	def glOrtho(): Unit = {
	}

	def glPixelStore(): Unit = {
	}

	def glPointParameter(): Unit = {
	}

	def glPointSize(): Unit = {
	}

	def glPolygonOffset(): Unit = {
	}

	def glPopMatrix(): Unit = {
	}

	def glPushMatrix(): Unit = {
	}

	def glReadPixels(): Unit = {
	}

	def glRotate(): Unit = {
	}

	def glSampleCoverage(): Unit = {
	}

	def glScale(): Unit = {
	}

	def glScissor(): Unit = {
	}

	def glShadeModel(): Unit = {
	}

	def glStencilFunc(): Unit = {
	}

	def glStencilMask(): Unit = {
	}

	def glStencilOp(): Unit = {
	}

	def glTexCoordPointer(): Unit = {
	}

	def glTexEnv(): Unit = {
	}

	def glTexImage2D(): Unit = {
	}

	def glTexParameter(): Unit = {
	}

	def glTexSubImage2D(): Unit = {
	}

	def glTranslate(): Unit = {
	}

	def glVertexPointer(): Unit = {
	}

	def glViewport(): Unit = {
	}
}
